const TELEGRAM_DB=[
{"name":"ᴇʟɪᴛᴀ ᴍᴜᴢ♬","handle":"elitaa_music","s":419373,"v":102000,"c":"Казахстан","t":"Развлечения","l":"https://t.me/elitaa_music"},
{"name":"Dmwin 🏅🏅 CRYPTO","handle":"Crypto_Win_Gift_Codes","s":400906,"v":106,"c":"Казахстан","t":"Общие","l":"https://t.me/Crypto_Win_Gift_Codes"},
{"name":"Tengrinews.kz - Новости Казахстана","handle":"tengrinews","s":264073,"v":44000,"c":"Казахстан","t":"Новостные","l":"https://t.me/tengrinews"},
{"name":"Маргулан Сейсембай","handle":"MargulanSeissembai","s":216438,"v":45800,"c":"Казахстан","t":"Общие","l":"https://t.me/MargulanSeissembai"},
{"name":"Zakon.kz - Новости Казахстана и мира","handle":"zakonkz","s":206232,"v":21100,"c":"Казахстан","t":"Новостные","l":"https://t.me/zakonkz"},
{"name":"Казахстан Подешевле","handle":"podeshevlekz","s":197163,"v":51000,"c":"Казахстан","t":"Общие","l":"https://t.me/podeshevlekz"},
{"name":"Қазақша әндер | Музыка 2026","handle":"hit_kz","s":189204,"v":38000,"c":"Казахстан","t":"Развлечения","l":"https://t.me/hit_kz"},
{"name":"ZTB NEWS - Новости Казахстана","handle":"ztb_qaz","s":183081,"v":24600,"c":"Казахстан","t":"Новостные","l":"https://t.me/ztb_qaz"},
{"name":"ҚАЗАҚША🕊Музыкалар🎧Андер","handle":"Kazakshax","s":180132,"v":21500,"c":"Казахстан","t":"Развлечения","l":"https://t.me/Kazakshax"},
{"name":"𝐌𝐘 𝐒𝐎𝐔𝐋 | MUSIC 🎶","handle":"mysoul_music","s":179260,"v":29800,"c":"Казахстан","t":"Развлечения","l":"https://t.me/mysoul_music"},
{"name":"VK Music | Новинки | Автозвук","handle":"vkmusic_muzyka","s":161382,"v":8000,"c":"Казахстан","t":"Развлечения","l":"https://t.me/vkmusic_muzyka"},
{"name":"Хит әндер | Казакша андер","handle":"xit_an","s":158432,"v":15000,"c":"Казахстан","t":"Развлечения","l":"https://t.me/xit_an"},
{"name":"Билеты на чартерные рейсы от Step to Travel","handle":"charterticketsme","s":154889,"v":2900,"c":"Казахстан","t":"Общие","l":"https://t.me/charterticketsme"},
{"name":"𝗘𝗟𝗜𝗧𝗔 𝗠𝗨𝗦𝗜𝗖","handle":"elitamusic_kaz","s":151536,"v":24500,"c":"Казахстан","t":"Развлечения","l":"https://t.me/elitamusic_kaz"},
{"name":"TESTCENTERKZ","handle":"uto92","s":146897,"v":31900,"c":"Казахстан","t":"Образование","l":"https://t.me/uto92"},
{"name":"ORDA","handle":"orda_kz","s":146032,"v":19500,"c":"Казахстан","t":"Новостные","l":"https://t.me/orda_kz"},
{"name":"Турагентство HT.KZ","handle":"HT_kz","s":143996,"v":9700,"c":"Казахстан","t":"Общие","l":"https://t.me/HT_kz"},
{"name":"Қазақша Әндер | Казакша Музыкалар","handle":"ANDERQM","s":127345,"v":35800,"c":"Казахстан","t":"Развлечения","l":"https://t.me/ANDERQM"},
{"name":"Qumash","handle":"qumash_kz","s":125899,"v":27800,"c":"Казахстан","t":"Общие","l":"https://t.me/qumash_kz"},
{"name":"Tim Wallpapers & Techno Time","handle":"tim_wallpapers","s":123937,"v":62600,"c":"Казахстан","t":"Общие","l":"https://t.me/tim_wallpapers"},
{"name":"Kozachkov offside","handle":"kozachkow","s":118719,"v":38800,"c":"Казахстан","t":"Общие","l":"https://t.me/kozachkow"},
{"name":"𝗘𝗟𝗜𝗧𝗔 𝗠𝗨𝗭 | 𝗞𝗔𝗭🇰🇿","handle":"elita_music_kz","s":113764,"v":19100,"c":"Казахстан","t":"Развлечения","l":"https://t.me/elita_music_kz"},
{"name":"ᴄᴀᴘssᴜʟʟᴀ ᴍᴜᴢ♬ | Хит әндер ♬","handle":"capssullamuz","s":109454,"v":11400,"c":"Казахстан","t":"Развлечения","l":"https://t.me/capssullamuz"},
{"name":"@𝗺𝘂𝘇𝘇𝘇.𝗸𝘇𝘇𝘇 |Хит Музыка🎵","handle":"kazakhmuzzone","s":105752,"v":50100,"c":"Казахстан","t":"Развлечения","l":"https://t.me/kazakhmuzzone"},
{"name":"Соққы және гол!","handle":"soqqyjanegoal","s":103013,"v":23300,"c":"Казахстан","t":"Спорт","l":"https://t.me/soqqyjanegoal"},
{"name":"YEDILOV online","handle":"yedilov_online","s":102460,"v":31400,"c":"Казахстан","t":"Общие","l":"https://t.me/yedilov_online"},
{"name":"Қазақша Андер","handle":"KAZAKSHA_MUZYKALAR","s":101409,"v":19900,"c":"Казахстан","t":"Развлечения","l":"https://t.me/KAZAKSHA_MUZYKALAR"},
{"name":"Папа Сиыр 🐮","handle":"fadisoska","s":93313,"v":18900,"c":"Казахстан","t":"Общие","l":"https://t.me/fadisoska"},
{"name":"ALTYN•DOP","handle":"altyn_dop_1","s":92008,"v":21900,"c":"Казахстан","t":"Общие","l":"https://t.me/altyn_dop_1"},
{"name":"Қазақша мультфильмдерҚоймасы","handle":"kazaksha_kinolarmen_filmder2","s":89471,"v":18800,"c":"Казахстан","t":"Развлечения","l":"https://t.me/kazaksha_kinolarmen_filmder2"},
{"name":"Dauletten.kz","handle":"dauletten_news","s":86514,"v":12100,"c":"Казахстан","t":"Новостные","l":"https://t.me/dauletten_news"},
{"name":"Қазақша әндер Музыка","handle":"zakonkzt","s":86380,"v":11600,"c":"Казахстан","t":"Новостные","l":"https://t.me/zakonkzt"},
{"name":"Qaz365.kz","handle":"qaz365kz","s":84121,"v":13500,"c":"Казахстан","t":"Общие","l":"https://t.me/qaz365kz"},
{"name":"KarGOO","handle":"karagandagoo","s":83737,"v":87400,"c":"Караганда","t":"Общие","l":"https://t.me/karagandagoo"},
{"name":"ҚАЗАҚША ФИЛЬМ 🎥","handle":"kazaksha_kino5757","s":83127,"v":16200,"c":"Казахстан","t":"Развлечения","l":"https://t.me/kazaksha_kino5757"},
{"name":"Обои на телефон","handle":"teloboii","s":83018,"v":6900,"c":"Казахстан","t":"Общие","l":"https://t.me/teloboii"},
{"name":"Аттестация 2026","handle":"attestasiyakz","s":81715,"v":20100,"c":"Казахстан","t":"Образование","l":"https://t.me/attestasiyakz"},
{"name":"Спойлеры с нами!","handle":"SpoilersAreWithUs","s":81491,"v":27900,"c":"Казахстан","t":"Развлечения","l":"https://t.me/SpoilersAreWithUs"},
{"name":"PRO КАДРЫ KZ","handle":"prokadrykz","s":80753,"v":16700,"c":"Казахстан","t":"Общие","l":"https://t.me/prokadrykz"},
{"name":"Көрнекіліктер дидактикалық материалдар","handle":"kornekilikter","s":79286,"v":19400,"c":"Казахстан","t":"Общие","l":"https://t.me/kornekilikter"},
{"name":"Қазақша мультфильмдер","handle":"kazaksha_kinolarmen_filmder","s":78049,"v":12200,"c":"Казахстан","t":"Развлечения","l":"https://t.me/kazaksha_kinolarmen_filmder"},
{"name":"Mr. Kolson","handle":"mrkolson","s":77793,"v":17100,"c":"Казахстан","t":"Общие","l":"https://t.me/mrkolson"},
{"name":"Aqorda 🇰🇿","handle":"aqorda_resmi","s":76903,"v":9200,"c":"Астана","t":"Новостные","l":"https://t.me/aqorda_resmi"},
{"name":"NUR.KZ - Новости Казахстана","handle":"newsnurkz","s":76398,"v":10300,"c":"Казахстан","t":"Новостные","l":"https://t.me/newsnurkz"},
{"name":"Қазақша кинолармен, фильмдер","handle":"multfilmder_kazaksha","s":76186,"v":19700,"c":"Казахстан","t":"Развлечения","l":"https://t.me/multfilmder_kazaksha"},
{"name":"Atameken Business - Новости Казахстана","handle":"atamekenbusiness","s":75297,"v":8000,"c":"Казахстан","t":"Новостные","l":"https://t.me/atamekenbusiness"},
{"name":"НЕХабар","handle":"nehabar","s":74388,"v":9200,"c":"Казахстан","t":"Общие","l":"https://t.me/nehabar"},
{"name":"TENGENOMIKA","handle":"tengenomika","s":73205,"v":11800,"c":"Казахстан","t":"Бизнес","l":"https://t.me/tengenomika"},
{"name":"Аренда квартира Алматы Подселение","handle":"kvartiry2","s":70638,"v":481,"c":"Алматы","t":"Недвижимость","l":"https://t.me/kvartiry2"},
{"name":"Фонд-бюро расследования коррупции","handle":"fund_anticorr","s":68304,"v":18000,"c":"Казахстан","t":"Новостные","l":"https://t.me/fund_anticorr"},
{"name":"EGOV.PRESS","handle":"egovpress","s":67880,"v":20800,"c":"Казахстан","t":"Новостные","l":"https://t.me/egovpress"},
{"name":"За нами уже выехали","handle":"Zanamiviehali","s":67088,"v":14800,"c":"Казахстан","t":"Общие","l":"https://t.me/Zanamiviehali"},
{"name":"JUZ40 ONLINE | ҰБТ 2026","handle":"juz40_online","s":66507,"v":7400,"c":"Казахстан","t":"Общие","l":"https://t.me/juz40_online"},
{"name":"Қазақша кітаптар","handle":"kzkitap","s":66360,"v":22500,"c":"Казахстан","t":"Образование","l":"https://t.me/kzkitap"},
{"name":"🇰🇿 𝐁𝐀𝐓𝐘𝐒 𝐌𝐔𝐙 🎧 | Хит әндер","handle":"batys_muztt","s":65929,"v":4400,"c":"Казахстан","t":"Развлечения","l":"https://t.me/batys_muztt"},
{"name":"Creative Asia","handle":"we_project","s":64712,"v":4200,"c":"Казахстан","t":"Общие","l":"https://t.me/we_project"},
{"name":"NiceDub – Қазақша дорама Делюкс Таксиі","handle":"nicedubfilm","s":64491,"v":26000,"c":"Казахстан","t":"Развлечения","l":"https://t.me/nicedubfilm"},
{"name":"Waysberg music 🇰🇿","handle":"waysbergmusic","s":63772,"v":50600,"c":"Казахстан","t":"Развлечения","l":"https://t.me/waysbergmusic"},
{"name":"🇰🇿 FINANCE.kz","handle":"FINANCEkaz","s":62580,"v":10900,"c":"Казахстан","t":"Бизнес","l":"https://t.me/FINANCEkaz"},
{"name":"Astanovka98","handle":"astanovka98","s":61934,"v":17800,"c":"Казахстан","t":"Общие","l":"https://t.me/astanovka98"},
{"name":"KVM TG Mobile Games","handle":"kvmobilegames","s":61772,"v":19000,"c":"Казахстан","t":"Общие","l":"https://t.me/kvmobilegames"},
{"name":"Aviasales.kz","handle":"AAAVIASALESKZ","s":61641,"v":9600,"c":"Казахстан","t":"Общие","l":"https://t.me/AAAVIASALESKZ"},
{"name":"ORDA STUDIO | ҚАЗАҚША ДЫБЫСТАМА","handle":"studioorda","s":61579,"v":24100,"c":"Казахстан","t":"Новостные","l":"https://t.me/studioorda"},
{"name":"ҚАЗАҚША ФИЛЬМ 🎥","handle":"kazaksha_muzykalarr_multfilm","s":60088,"v":12300,"c":"Казахстан","t":"Развлечения","l":"https://t.me/kazaksha_muzykalarr_multfilm"},
{"name":"ALIBEKOV","handle":"alibekovkz","s":60023,"v":15800,"c":"Казахстан","t":"Общие","l":"https://t.me/alibekovkz"},
{"name":"Қазақша кинолармен, фильмдерҚоймасы","handle":"multfilmder_kazaksha2","s":59470,"v":17300,"c":"Казахстан","t":"Развлечения","l":"https://t.me/multfilmder_kazaksha2"},
{"name":"Almaty Today","handle":"almatytoday","s":58321,"v":14600,"c":"Алматы","t":"Общие","l":"https://t.me/almatytoday"},
{"name":"Турагентство POEDEM.KZ","handle":"poedem_kz","s":58223,"v":4300,"c":"Казахстан","t":"Общие","l":"https://t.me/poedem_kz"},
{"name":"Алишер Бейсебай | Tech","handle":"alisherbeisebai","s":55404,"v":8000,"c":"Казахстан","t":"Общие","l":"https://t.me/alisherbeisebai"},
{"name":"ПЕЙІШ 2 | ҒАШЫҚПЫН САҒАН 🎬","handle":"peiysh2ga","s":54922,"v":22200,"c":"Казахстан","t":"Общие","l":"https://t.me/peiysh2ga"},
{"name":"Pirates Family • Roblox","handle":"bloxteamshop","s":54694,"v":1600,"c":"Казахстан","t":"Общие","l":"https://t.me/bloxteamshop"},
{"name":"ФИЛЬМЫ НА ВЕЧЕР🎥","handle":"kinowkanavecherr","s":53403,"v":7400,"c":"Казахстан","t":"Развлечения","l":"https://t.me/kinowkanavecherr"},
{"name":"Nomad Soul","handle":"nomadsoul","s":52815,"v":10100,"c":"Казахстан","t":"Развлечения","l":"https://t.me/nomadsoul"},
{"name":"Чартеры в Турцию от Step to Travel","handle":"charterticketstr","s":52202,"v":1400,"c":"Казахстан","t":"Общие","l":"https://t.me/charterticketstr"},
{"name":"БАСЕ","handle":"basekz","s":51912,"v":15500,"c":"Казахстан","t":"Общие","l":"https://t.me/basekz"},
{"name":"ҚАЗАҚША ФИЛЬМ 🎥","handle":"Kazaksha_multfilmm_kino","s":51715,"v":6500,"c":"Казахстан","t":"Развлечения","l":"https://t.me/Kazaksha_multfilmm_kino"},
{"name":"СЫНЫП ЖЕТ. ҚР. КЛ. РУК. РК","handle":"Cinfshetekshi","s":50944,"v":21800,"c":"Казахстан","t":"Общие","l":"https://t.me/Cinfshetekshi"},
{"name":"БЕЙИШ | ПЕЙІШ | АДАМ БОЛ | ҚЫЗЫМ","handle":"abaibol_kory","s":50429,"v":37500,"c":"Казахстан","t":"Общие","l":"https://t.me/abaibol_kory"},
{"name":"ҚР Ғылым және жоғары білім министрлігі","handle":"gylym_jogary_bilim","s":49932,"v":2900,"c":"Казахстан","t":"Образование","l":"https://t.me/gylym_jogary_bilim"},
{"name":"SADRADDIN","handle":"sadraddin707","s":48905,"v":23800,"c":"Казахстан","t":"Общие","l":"https://t.me/sadraddin707"},
{"name":"Балқия Балтабай","handle":"balkia_baltabay","s":48647,"v":6400,"c":"Казахстан","t":"Общие","l":"https://t.me/balkia_baltabay"},
{"name":"Аренда квартира Алматы Подселение","handle":"arenba67","s":47810,"v":490,"c":"Алматы","t":"Общие","l":"https://t.me/arenba67"},
{"name":"Qazaqstan.tv","handle":"qazaqstantv","s":47332,"v":1600,"c":"Казахстан","t":"Общие","l":"https://t.me/qazaqstantv"},
{"name":"ALTYN DOP RESMI","handle":"altyndop1","s":46884,"v":12300,"c":"Казахстан","t":"Общие","l":"https://t.me/altyndop1"},
{"name":"EgovKzBot2.0","handle":"EgovKzBot2_01","s":46285,"v":3400,"c":"Казахстан","t":"Общие","l":"https://t.me/EgovKzBot2_01"},
{"name":"KAZAKH_INFORM","handle":"kazakh_inform","s":46069,"v":5100,"c":"Казахстан","t":"Общие","l":"https://t.me/kazakh_inform"},
{"name":"grants.kz","handle":"grants_scholarships","s":45992,"v":5100,"c":"Казахстан","t":"Общие","l":"https://t.me/grants_scholarships"},
{"name":"🇰🇿ҚР ОҚУ-АҒАРТУ МИНИСТРЛІГІ","handle":"oqu_agartu","s":45642,"v":3000,"c":"Казахстан","t":"Общие","l":"https://t.me/oqu_agartu"},
{"name":"KazTAG","handle":"kaztag_tg","s":44537,"v":7700,"c":"Казахстан","t":"Общие","l":"https://t.me/kaztag_tg"},
{"name":"Sputnik Казахстан","handle":"sputnikKZ","s":43903,"v":6200,"c":"Казахстан","t":"Общие","l":"https://t.me/sputnikKZ"},
{"name":"ZHEST_KZ","handle":"zhest_kz_official","s":42487,"v":4600,"c":"Казахстан","t":"Общие","l":"https://t.me/zhest_kz_official"},
{"name":"WATAKATO NEWS","handle":"watakato","s":39866,"v":19400,"c":"Казахстан","t":"Новостные","l":"https://t.me/watakato"},
{"name":"Седьмой канал","handle":"tv7_kaz","s":39493,"v":4900,"c":"Казахстан","t":"Общие","l":"https://t.me/tv7_kaz"},
{"name":"𝐏𝐑𝐀𝐈𝐃𝐄 𝐌𝐔𝐙𝐈𝐂 🎧","handle":"pride_muzzzz","s":39453,"v":15800,"c":"Казахстан","t":"Общие","l":"https://t.me/pride_muzzzz"},
{"name":"Khabar","handle":"khabartv_kz","s":39000,"v":4300,"c":"Казахстан","t":"Общие","l":"https://t.me/khabartv_kz"},
{"name":"QAZSPORTTV","handle":"qazsporttv","s":38626,"v":4400,"c":"Казахстан","t":"Спорт","l":"https://t.me/qazsporttv"},
{"name":"Типичный Павлодар - шок tipavlo","handle":"tipavlo","s":38625,"v":15600,"c":"Павлодар","t":"Общие","l":"https://t.me/tipavlo"},
{"name":"YerSport","handle":"ErsinSport","s":38488,"v":9000,"c":"Казахстан","t":"Спорт","l":"https://t.me/ErsinSport"},
{"name":"Тулпар.Media","handle":"mediatulpar","s":37161,"v":9900,"c":"Казахстан","t":"Общие","l":"https://t.me/mediatulpar"},
{"name":"112 KZ","handle":"qr_tjm","s":36660,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/qr_tjm"},
{"name":"EL.INFO","handle":"elinfo_kz","s":35198,"v":1600,"c":"Казахстан","t":"Общие","l":"https://t.me/elinfo_kz"},
{"name":"Атас отандас!","handle":"atasotandas","s":35004,"v":9700,"c":"Казахстан","t":"Общие","l":"https://t.me/atasotandas"},
{"name":"Спорт Шредингера","handle":"sportilinet","s":33760,"v":9000,"c":"Казахстан","t":"Спорт","l":"https://t.me/sportilinet"},
{"name":"АРИСТОКРАТ","handle":"kitapkz1","s":33388,"v":5800,"c":"Казахстан","t":"Образование","l":"https://t.me/kitapkz1"},
{"name":"Central Media24.kz","handle":"CentralMedia24kz","s":32544,"v":18800,"c":"Казахстан","t":"Общие","l":"https://t.me/CentralMedia24kz"},
{"name":"CMN.KZ","handle":"CMN_KZ","s":31844,"v":3700,"c":"Казахстан","t":"Общие","l":"https://t.me/CMN_KZ"},
{"name":"OCTAGON | MMA LEAGUE","handle":"octagonleague","s":31719,"v":9300,"c":"Казахстан","t":"Общие","l":"https://t.me/octagonleague"},
{"name":"Informburo.kz – Новости Казахстана","handle":"informburo_kz","s":31053,"v":2900,"c":"Казахстан","t":"Новостные","l":"https://t.me/informburo_kz"},
{"name":"Казинформ","handle":"kazinform_news","s":30675,"v":1300,"c":"Казахстан","t":"Новостные","l":"https://t.me/kazinform_news"},
{"name":"AFFILIATE KAZAHSTAN","handle":"Affiliatekazahstan","s":30667,"v":106,"c":"Казахстан","t":"Общие","l":"https://t.me/Affiliatekazahstan"},
{"name":"Kornekilikter_kaz(Тегін канал)","handle":"kornekilikter_kaz","s":30527,"v":22600,"c":"Казахстан","t":"Общие","l":"https://t.me/kornekilikter_kaz"},
{"name":"SPORTS.KZ","handle":"allsportskz","s":30115,"v":3900,"c":"Казахстан","t":"Спорт","l":"https://t.me/allsportskz"},
{"name":"kerek.pv","handle":"kerekpv","s":29890,"v":7000,"c":"Казахстан","t":"Общие","l":"https://t.me/kerekpv"},
{"name":"Shishkin_like","handle":"shishkin_like","s":29889,"v":3700,"c":"Казахстан","t":"Общие","l":"https://t.me/shishkin_like"},
{"name":"Полезный Казахстан","handle":"useful_qazaqstan","s":29532,"v":7200,"c":"Казахстан","t":"Общие","l":"https://t.me/useful_qazaqstan"},
{"name":"Көрнекіліктер әдіс тәсілдер Тегін көрнекіліктер","handle":"kornekilikter_kz","s":28873,"v":11800,"c":"Казахстан","t":"Общие","l":"https://t.me/kornekilikter_kz"},
{"name":"HALYQSTAN 🇰🇿","handle":"halyqstan","s":28846,"v":8800,"c":"Казахстан","t":"Общие","l":"https://t.me/halyqstan"},
{"name":"ҰБТ 2026 / UBT Academy 2026","handle":"ubt_academy","s":27131,"v":2400,"c":"Казахстан","t":"Общие","l":"https://t.me/ubt_academy"},
{"name":"ВЫХОД К ПРАВДЕ","handle":"ulysmediatg","s":26892,"v":3500,"c":"Казахстан","t":"Общие","l":"https://t.me/ulysmediatg"},
{"name":"Мұғалімдерге материалдар","handle":"kornekiliktermaterialdar","s":26817,"v":5900,"c":"Казахстан","t":"Общие","l":"https://t.me/kornekiliktermaterialdar"},
{"name":"Креативті педагог👩🏻‍🏫","handle":"kreativtipedagogkz","s":26421,"v":11200,"c":"Казахстан","t":"Еда/Досуг","l":"https://t.me/kreativtipedagogkz"},
{"name":"KöpSöz","handle":"kopsozkz","s":26358,"v":2500,"c":"Казахстан","t":"Общие","l":"https://t.me/kopsozkz"},
{"name":"Көрнекіліктер әдіс тәсілдер","handle":"adistasill","s":25892,"v":9800,"c":"Казахстан","t":"Общие","l":"https://t.me/adistasill"},
{"name":"gov4c.kz","handle":"gov4c_resmi","s":25399,"v":4800,"c":"Казахстан","t":"Общие","l":"https://t.me/gov4c_resmi"},
{"name":"Казахский чуваш","handle":"kazchuvash","s":25361,"v":7100,"c":"Казахстан","t":"Общие","l":"https://t.me/kazchuvash"},
{"name":"QOGAM by SATZHANGRAM","handle":"qogamnews","s":25292,"v":1400,"c":"Казахстан","t":"Новостные","l":"https://t.me/qogamnews"},
{"name":"BES.media","handle":"bessimptomno","s":25066,"v":1900,"c":"Казахстан","t":"Общие","l":"https://t.me/bessimptomno"},
{"name":"Zerdeli Online | Алтын Сақа","handle":"altynsaqa_official","s":23771,"v":3200,"c":"Казахстан","t":"Общие","l":"https://t.me/altynsaqa_official"},
{"name":"Криминальный Казахстан 🔞","handle":"kriminal_kazakhstan","s":22971,"v":7900,"c":"Казахстан","t":"Общие","l":"https://t.me/kriminal_kazakhstan"},
{"name":"Ұстазға керек және көмек💡","handle":"sk9005","s":22967,"v":6000,"c":"Казахстан","t":"Общие","l":"https://t.me/sk9005"},
{"name":"LADA.KZ - Новости Мангистау и Актау","handle":"ladakz","s":22809,"v":3800,"c":"Актау","t":"Новостные","l":"https://t.me/ladakz"},
{"name":"Eyad Trader Quotex Bot 🤖1️⃣","handle":"EyadTraderBot","s":22756,"v":108,"c":"Казахстан","t":"Общие","l":"https://t.me/EyadTraderBot"},
{"name":"Алтын Адам","handle":"AltynAdamEsyk","s":22270,"v":9900,"c":"Казахстан","t":"Общие","l":"https://t.me/AltynAdamEsyk"},
{"name":"Atameken Business - Жаңалықтар","handle":"atamekenbusiness_qaz","s":21430,"v":2100,"c":"Казахстан","t":"Бизнес","l":"https://t.me/atamekenbusiness_qaz"},
{"name":"МОЙ СЕМЕЙ","handle":"gorodsemey","s":21362,"v":13300,"c":"Семей","t":"Общие","l":"https://t.me/gorodsemey"},
{"name":"ТАРИХ| ҰБТ 2026","handle":"tarih_ubt_kz","s":21267,"v":3500,"c":"Казахстан","t":"Общие","l":"https://t.me/tarih_ubt_kz"},
{"name":"Kommentator_Maulen","handle":"Kommentator_Maulen","s":21267,"v":3500,"c":"Казахстан","t":"Общие","l":"https://t.me/Kommentator_Maulen"},
{"name":"ҚАҢТАР ҰБТ 2026 | ЯНВАРСКОЕ ЕНТ 2026 UbtSmart💡","handle":"UbtSmart","s":21253,"v":7100,"c":"Казахстан","t":"Общие","l":"https://t.me/UbtSmart"},
{"name":"Kris.p.media","handle":"almatykrispi","s":21218,"v":1500,"c":"Алматы","t":"Общие","l":"https://t.me/almatykrispi"},
{"name":"СЛИВ ҰБТ 2026","handle":"ubt_sliv_2026","s":21165,"v":4600,"c":"Казахстан","t":"Общие","l":"https://t.me/ubt_sliv_2026"},
{"name":"Отдел образования города Темиртау","handle":"ootemirtau","s":21010,"v":24500,"c":"Казахстан","t":"Образование","l":"https://t.me/ootemirtau"},
{"name":"EgovKzBot2.0 Новости Казахстана на русском","handle":"EgovKzBot2_03","s":20944,"v":1100,"c":"Казахстан","t":"Новостные","l":"https://t.me/EgovKzBot2_03"},
{"name":"Левобережный банкстер KZ 🇰🇿","handle":"kzbankster","s":20767,"v":4900,"c":"Казахстан","t":"Общие","l":"https://t.me/kzbankster"},
{"name":"Астана - Что? Где? Когда?","handle":"myastanacity","s":19561,"v":4800,"c":"Астана","t":"Общие","l":"https://t.me/myastanacity"},
{"name":"Отзывы Карго","handle":"otzyvkargo","s":19100,"v":6000,"c":"Казахстан","t":"Общие","l":"https://t.me/otzyvkargo"},
{"name":"ЕНТ MOMMY | Тесты ЕНТ, Сливы, Полезные материалы","handle":"ent_mommy","s":18990,"v":2700,"c":"Казахстан","t":"Общие","l":"https://t.me/ent_mommy"},
{"name":"Massaget NEWS","handle":"massaget_news","s":18810,"v":1500,"c":"Казахстан","t":"Новостные","l":"https://t.me/massaget_news"},
{"name":"Фонд «Даму»","handle":"funddamu","s":18753,"v":2100,"c":"Казахстан","t":"Общие","l":"https://t.me/funddamu"},
{"name":"Бастауыш сынып | USTAZ TILEGI","handle":"bastauysh","s":18513,"v":3000,"c":"Казахстан","t":"Общие","l":"https://t.me/bastauysh"},
{"name":"iKOMEK109 Astana 24/7","handle":"ikomek109","s":18000,"v":7200,"c":"Астана","t":"Общие","l":"https://t.me/ikomek109"},
{"name":"KeyNews","handle":"allkeynews","s":17980,"v":2800,"c":"Казахстан","t":"Новостные","l":"https://t.me/allkeynews"},
{"name":"ДҮНИЕЖҮЗІ ТАРИХЫ | ҰБТ | DZHT TEAM","handle":"dzht_team","s":17842,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/dzht_team"},
{"name":"Квартира с террасой","handle":"kvartira_s_terrasoy","s":17787,"v":4900,"c":"Казахстан","t":"Недвижимость","l":"https://t.me/kvartira_s_terrasoy"},
{"name":"Дряблости нет","handle":"litsomolodost","s":17770,"v":869,"c":"Казахстан","t":"Общие","l":"https://t.me/litsomolodost"},
{"name":"Hola News","handle":"holanewskz","s":17391,"v":3500,"c":"Казахстан","t":"Новостные","l":"https://t.me/holanewskz"},
{"name":"artsport.kz","handle":"artsportedukz","s":17328,"v":3200,"c":"Казахстан","t":"Спорт","l":"https://t.me/artsportedukz"},
{"name":"РЕСПУБЛИКА.KZ.media","handle":"respublikaKZmediaNEWS","s":17051,"v":2700,"c":"Казахстан","t":"Новостные","l":"https://t.me/respublikaKZmediaNEWS"},
{"name":"Smart олимпиада","handle":"smart_kz","s":16982,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/smart_kz"},
{"name":"Kazpress.kz","handle":"qazpress_kz","s":16981,"v":1600,"c":"Казахстан","t":"Новостные","l":"https://t.me/qazpress_kz"},
{"name":"СКУЛХАК: СОР, СОЧ, БЖБ, ТЖБ","handle":"schoolhack_1","s":16980,"v":5700,"c":"Казахстан","t":"Общие","l":"https://t.me/schoolhack_1"},
{"name":"БИОЛОГИЯ ҰБТ | АЙБОТА ЕКПІН","handle":"biologyubt50","s":16877,"v":5200,"c":"Казахстан","t":"Общие","l":"https://t.me/biologyubt50"},
{"name":"Жаңалықтар - Stan.kz","handle":"stankznews","s":16687,"v":1700,"c":"Казахстан","t":"Новостные","l":"https://t.me/stankznews"},
{"name":"𝐓𝐄𝐍𝐁𝐈𝐋 𝐃𝐎𝐏","handle":"tenbildoplive","s":16617,"v":4800,"c":"Казахстан","t":"Общие","l":"https://t.me/tenbildoplive"},
{"name":"Крис Пи Тараз","handle":"VchTr3SQXGKyVnB9","s":16559,"v":7300,"c":"Тараз","t":"Общие","l":"https://t.me/VchTr3SQXGKyVnB9"},
{"name":"ABAI UNIVERSITY","handle":"abai_univer","s":16224,"v":6100,"c":"Казахстан","t":"Общие","l":"https://t.me/abai_univer"},
{"name":"Forbes Kazakhstan","handle":"ForbesKaz","s":16061,"v":3500,"c":"Казахстан","t":"Общие","l":"https://t.me/ForbesKaz"},
{"name":"Sports24.kz","handle":"sports24_kz","s":16061,"v":597,"c":"Казахстан","t":"Спорт","l":"https://t.me/sports24_kz"},
{"name":"Барсамен Бірге","handle":"barcamenbirge","s":15972,"v":5300,"c":"Казахстан","t":"Общие","l":"https://t.me/barcamenbirge"},
{"name":"СЛИВЫ ЕНТ 2026 | ҰБТ СЛИВ 2026","handle":"entslivskz","s":15876,"v":1100,"c":"Казахстан","t":"Общие","l":"https://t.me/entslivskz"},
{"name":"DARYN RSPC","handle":"daryn_centre","s":15779,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/daryn_centre"},
{"name":"Квалтест НКТ, ОЗП, ПББ 2026","handle":"nkttest","s":15728,"v":8800,"c":"Казахстан","t":"Образование","l":"https://t.me/nkttest"},
{"name":"Freedom QJ League","handle":"qjleague","s":15723,"v":1400,"c":"Казахстан","t":"Общие","l":"https://t.me/qjleague"},
{"name":"БІРІНШІ БОЛ","handle":"b1rinshibol","s":15595,"v":1600,"c":"Казахстан","t":"Общие","l":"https://t.me/b1rinshibol"},
{"name":"ABAI NEWS","handle":"abainewskz","s":15550,"v":3500,"c":"Казахстан","t":"Новостные","l":"https://t.me/abainewskz"},
{"name":"Наша Газета (Костанай)","handle":"NashaGazetaKst","s":15459,"v":2700,"c":"Казахстан","t":"Общие","l":"https://t.me/NashaGazetaKst"},
{"name":"Көрнекіліктер дидактикалық материалдар | USTAZ TILEGI","handle":"material_ust","s":15414,"v":2500,"c":"Казахстан","t":"Общие","l":"https://t.me/material_ust"},
{"name":"KUSPEKOV OLZHAS🇰🇿","handle":"kuspekov_olzhas_public","s":15167,"v":1500,"c":"Казахстан","t":"Общие","l":"https://t.me/kuspekov_olzhas_public"},
{"name":"AstanaTV","handle":"astana_arnasy","s":14910,"v":209,"c":"Астана","t":"Общие","l":"https://t.me/astana_arnasy"},
{"name":"ҰБТ ЕНТ 2026","handle":"entubt2026zh","s":14811,"v":2100,"c":"Казахстан","t":"Общие","l":"https://t.me/entubt2026zh"},
{"name":"The Village Казахстан🇰🇿","handle":"villagekazakhstan","s":14767,"v":1500,"c":"Казахстан","t":"Общие","l":"https://t.me/villagekazakhstan"},
{"name":"Tengri Almaty","handle":"tengrialmaty","s":14764,"v":3800,"c":"Алматы","t":"Общие","l":"https://t.me/tengrialmaty"},
{"name":"💖استوری های خاص اینستاگرامی، کلیپ، موزیک ویدیو💖","handle":"Akstalaiy","s":14699,"v":289,"c":"Казахстан","t":"Общие","l":"https://t.me/Akstalaiy"},
{"name":"TRUE STORY KZ","handle":"truestorykz","s":14684,"v":2600,"c":"Казахстан","t":"Общие","l":"https://t.me/truestorykz"},
{"name":"Fonteam","handle":"fonteamkz","s":14571,"v":4400,"c":"Казахстан","t":"Общие","l":"https://t.me/fonteamkz"},
{"name":"“ҚАЗАҚ ТІЛІ МЕН ҚАЗАҚ ӘДЕБИЕТІ”","handle":"kazaktilimenadebiet1TEGINTOP","s":14420,"v":8600,"c":"Казахстан","t":"Общие","l":"https://t.me/kazaktilimenadebiet1TEGINTOP"},
{"name":"ДОДА","handle":"dodatimes","s":14355,"v":3600,"c":"Казахстан","t":"Общие","l":"https://t.me/dodatimes"},
{"name":"«Қайрат» ФК | FC Kairat Almaty","handle":"fc_kairat","s":14275,"v":4300,"c":"Алматы","t":"Общие","l":"https://t.me/fc_kairat"},
{"name":"🔴KING RING🔴","handle":"kingringkz","s":14250,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/kingringkz"},
{"name":"ҚОЛБЕТ","handle":"kolbetkz","s":14187,"v":4600,"c":"Казахстан","t":"Общие","l":"https://t.me/kolbetkz"},
{"name":"Спорт жаңалықтары | Руслан Бақытжан","handle":"sportqazaq","s":14130,"v":2700,"c":"Казахстан","t":"Спорт","l":"https://t.me/sportqazaq"},
{"name":"ҚР ЖОҒАРҒЫ СОТЫ","handle":"Jogargy_sot","s":14121,"v":1400,"c":"Казахстан","t":"Общие","l":"https://t.me/Jogargy_sot"},
{"name":"Zidan4eg Live","handle":"zidan4eglivekz","s":14063,"v":1500,"c":"Казахстан","t":"Общие","l":"https://t.me/zidan4eglivekz"},
{"name":"OSMANOV - О Рынке Недвижимости Казахстана","handle":"osmanovblog","s":14061,"v":6200,"c":"Казахстан","t":"Недвижимость","l":"https://t.me/osmanovblog"},
{"name":"Алматы - Казахстан","handle":"kazakhstan113","s":14029,"v":3200,"c":"Алматы","t":"Общие","l":"https://t.me/kazakhstan113"},
{"name":"Soqqy Live. Әлімжан Асқар","handle":"soqqylive","s":14023,"v":3700,"c":"Казахстан","t":"Общие","l":"https://t.me/soqqylive"},
{"name":"ҚР Қорғаныс министрлігі / Минобороны РК / Ministry of Defense of the RK 🇰🇿","handle":"modgovkz","s":14018,"v":2000,"c":"Казахстан","t":"Общие","l":"https://t.me/modgovkz"},
{"name":"Ösim","handle":"osim_media","s":13826,"v":2200,"c":"Казахстан","t":"Общие","l":"https://t.me/osim_media"},
{"name":"ҚТЖ PRESS","handle":"railways_kz","s":13601,"v":2600,"c":"Казахстан","t":"Новостные","l":"https://t.me/railways_kz"},
{"name":"Tengri Astana","handle":"tengriastana","s":13536,"v":3300,"c":"Астана","t":"Общие","l":"https://t.me/tengriastana"},
{"name":"Azattyq - Азаттык","handle":"RadioAzattyq","s":13530,"v":2600,"c":"Казахстан","t":"Общие","l":"https://t.me/RadioAzattyq"},
{"name":"ГЕОГРАФИЯ ҰБТ | GEONLINE","handle":"geonlinekz","s":13491,"v":1700,"c":"Казахстан","t":"Общие","l":"https://t.me/geonlinekz"},
{"name":"Креативті ұстаз / aigul_ustaz","handle":"Aigul_kreatibti_ustaz","s":13463,"v":3600,"c":"Казахстан","t":"Общие","l":"https://t.me/Aigul_kreatibti_ustaz"},
{"name":"krivosheev.wtf","handle":"KrivosheyevD","s":13381,"v":2600,"c":"Казахстан","t":"Общие","l":"https://t.me/KrivosheyevD"},
{"name":"ҰЯТ ЕМЕС!","handle":"uyateemes","s":13190,"v":4200,"c":"Казахстан","t":"Общие","l":"https://t.me/uyateemes"},
{"name":"ҰБТ Биология - Химия | Малика Ильяс","handle":"malikailyas","s":13065,"v":2200,"c":"Казахстан","t":"Общие","l":"https://t.me/malikailyas"},
{"name":"PARANOIA.KZ","handle":"paranoiakz","s":13040,"v":5100,"c":"Казахстан","t":"Общие","l":"https://t.me/paranoiakz"},
{"name":"Oy.kz | Платные опросы Казахстан","handle":"oy_kz_official","s":12989,"v":3700,"c":"Казахстан","t":"Общие","l":"https://t.me/oy_kz_official"},
{"name":"ATYRAUOIL 📰","handle":"atyrauoill","s":12900,"v":1800,"c":"Атырау","t":"Общие","l":"https://t.me/atyrauoill"},
{"name":"GOAL KZ | Қазақ футболы | Футбол Казахстана","handle":"goalkz_official","s":12828,"v":4000,"c":"Казахстан","t":"Спорт","l":"https://t.me/goalkz_official"},
{"name":"Новости КТК","handle":"ktknews","s":12806,"v":985,"c":"Казахстан","t":"Новостные","l":"https://t.me/ktknews"},
{"name":"Общественная безопасность Казахстан🇰🇿","handle":"nordkazakh89","s":12561,"v":1900,"c":"Казахстан","t":"Общие","l":"https://t.me/nordkazakh89"},
{"name":"Фабрицио ақпараты","handle":"romanokz","s":12554,"v":3100,"c":"Казахстан","t":"Общие","l":"https://t.me/romanokz"},
{"name":"МАТЕМ САУАТТЫЛЫҚ | ҰБТ | JUZ40","handle":"juz40_matsau","s":12444,"v":2700,"c":"Казахстан","t":"Общие","l":"https://t.me/juz40_matsau"},
{"name":"Казахстан и все-все-все","handle":"geo_2019","s":12438,"v":3000,"c":"Казахстан","t":"Общие","l":"https://t.me/geo_2019"},
{"name":"Match KZ","handle":"kzmatch","s":12372,"v":2500,"c":"Казахстан","t":"Общие","l":"https://t.me/kzmatch"},
{"name":"Сабақ жоспарлары | Көрнекіліктер","handle":"ustaz_test","s":12310,"v":841,"c":"Казахстан","t":"Образование","l":"https://t.me/ustaz_test"},
{"name":"БИОЛОГИЯ-ХИМИЯ ҰБТ 2025 | Әсел Молдабай","handle":"glucose_biology","s":12147,"v":1300,"c":"Казахстан","t":"Общие","l":"https://t.me/glucose_biology"},
{"name":"ЖАУЫНГЕР","handle":"sportmma_051","s":12119,"v":578,"c":"Казахстан","t":"Спорт","l":"https://t.me/sportmma_051"},
{"name":"Наш Спорт","handle":"sports_novostyi","s":12076,"v":6300,"c":"Казахстан","t":"Спорт","l":"https://t.me/sports_novostyi"},
{"name":"Kursiv.Media","handle":"kursivm","s":11934,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/kursivm"},
{"name":"Kris_p_almaty","handle":"kris_p_almaty_official","s":11888,"v":1900,"c":"Алматы","t":"Общие","l":"https://t.me/kris_p_almaty_official"},
{"name":"ПЕДАГОГИ КАЗАХСТАНА","handle":"pedagog_kz","s":11763,"v":991,"c":"Казахстан","t":"Еда/Досуг","l":"https://t.me/pedagog_kz"},
{"name":"OnlyGrants | Подготовка ЕНТ 2026","handle":"onlygrants_ru","s":11666,"v":2400,"c":"Казахстан","t":"Общие","l":"https://t.me/onlygrants_ru"},
{"name":"AQ$HANEWS","handle":"akshanews","s":11644,"v":613,"c":"Казахстан","t":"Новостные","l":"https://t.me/akshanews"},
{"name":"Естімеген елде көп","handle":"estimegeneldekoop","s":11587,"v":2000,"c":"Казахстан","t":"Общие","l":"https://t.me/estimegeneldekoop"},
{"name":"DALA INSIDE","handle":"dalainside","s":11540,"v":10500,"c":"Казахстан","t":"Общие","l":"https://t.me/dalainside"},
{"name":"Erteńmedia","handle":"ertenmedia","s":11539,"v":3700,"c":"Казахстан","t":"Общие","l":"https://t.me/ertenmedia"},
{"name":"Astana Daryny","handle":"astanadaryny","s":11515,"v":3800,"c":"Астана","t":"Общие","l":"https://t.me/astanadaryny"},
{"name":"Твой Алматы","handle":"youralmaty","s":11501,"v":4200,"c":"Алматы","t":"Общие","l":"https://t.me/youralmaty"},
{"name":"Jaidarman Production","handle":"JAIDARMANofficials","s":11431,"v":3300,"c":"Казахстан","t":"Общие","l":"https://t.me/JAIDARMANofficials"},
{"name":"Azattyq - Азаттық","handle":"azattyq","s":11384,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/azattyq"},
{"name":"Qazaqparat","handle":"QazAqparat_kz","s":11367,"v":247,"c":"Казахстан","t":"Общие","l":"https://t.me/QazAqparat_kz"},
{"name":"eKaraganda.kz","handle":"ekarkz","s":11366,"v":2300,"c":"Караганда","t":"Общие","l":"https://t.me/ekarkz"},
{"name":"Маркетинг в Казахстане ⛩","handle":"marketologyblog","s":11300,"v":1600,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/marketologyblog"},
{"name":"Химия-Биология мектебі | Бауыржан ағай","handle":"kzchem","s":11286,"v":1900,"c":"Казахстан","t":"Общие","l":"https://t.me/kzchem"},
{"name":"География ҰБТ 2026","handle":"geography0011","s":11167,"v":1700,"c":"Казахстан","t":"Общие","l":"https://t.me/geography0011"},
{"name":"AmanVIBE 🎙️","handle":"eldar_amanvibe","s":11019,"v":3600,"c":"Казахстан","t":"Общие","l":"https://t.me/eldar_amanvibe"},
{"name":"barys_official","handle":"hcbaryskz","s":10822,"v":4700,"c":"Казахстан","t":"Общие","l":"https://t.me/hcbaryskz"},
{"name":"JOO | ҰБТ 2026","handle":"jookzchannel","s":10767,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/jookzchannel"},
{"name":"Tengri.kz","handle":"tengri_kz","s":10737,"v":1600,"c":"Казахстан","t":"Общие","l":"https://t.me/tengri_kz"},
{"name":"Педагог-KZ","handle":"pedagogkz_kz","s":10689,"v":858,"c":"Казахстан","t":"Еда/Досуг","l":"https://t.me/pedagogkz_kz"},
{"name":"КАРАКАЛПАКСТАН","handle":"KARAKALPAK_janaliqlari","s":10670,"v":3000,"c":"Казахстан","t":"Общие","l":"https://t.me/KARAKALPAK_janaliqlari"},
{"name":"Мектепалды даярлық тобы | USTAZ TILEGI","handle":"kornekilik_uzdik","s":10617,"v":1600,"c":"Казахстан","t":"Общие","l":"https://t.me/kornekilik_uzdik"},
{"name":"JexeNews","handle":"jexenews","s":10596,"v":1400,"c":"Казахстан","t":"Новостные","l":"https://t.me/jexenews"},
{"name":"🇰🇿$hapalaq","handle":"Shapalaqkz","s":10528,"v":834,"c":"Казахстан","t":"Общие","l":"https://t.me/Shapalaqkz"},
{"name":"ХИМИЯ | ҰБТ | JUZ40","handle":"JUZ40C","s":10508,"v":1500,"c":"Казахстан","t":"Общие","l":"https://t.me/JUZ40C"},
{"name":"CAUÊ BORGES","handle":"caueborgesfree","s":10466,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/caueborgesfree"},
{"name":"Мұғалімге көмек","handle":"Shynarkurmangali","s":10350,"v":4500,"c":"Казахстан","t":"Общие","l":"https://t.me/Shynarkurmangali"},
{"name":"🌀Тосканбаев Арман | Бизнес мышление","handle":"toskanbayev","s":10249,"v":1500,"c":"Казахстан","t":"Бизнес","l":"https://t.me/toskanbayev"},
{"name":"СЛИВЫ ЕНТ 2026 | REGION","handle":"EHTREGIONKZ","s":10199,"v":2400,"c":"Казахстан","t":"Общие","l":"https://t.me/EHTREGIONKZ"},
{"name":"Satbayev Time | Что нового?","handle":"satbayevnews","s":9923,"v":6100,"c":"Казахстан","t":"Новостные","l":"https://t.me/satbayevnews"},
{"name":"Футбол – бұл өмір!","handle":"futbigkz","s":9814,"v":1700,"c":"Казахстан","t":"Общие","l":"https://t.me/futbigkz"},
{"name":"СЛИВЫ ЕНТ 2026","handle":"ent_slivkikz","s":9709,"v":575,"c":"Казахстан","t":"Общие","l":"https://t.me/ent_slivkikz"},
{"name":"QR PEDAGOGIKALÍQ SHEBERLIK ORAYÍ","handle":"malakanews","s":9657,"v":475,"c":"Казахстан","t":"Новостные","l":"https://t.me/malakanews"},
{"name":"Тотальный футбол KZ⚽️+ Инсайдерская информация из мира казахстанского спорта","handle":"qazpreml2","s":9651,"v":3600,"c":"Казахстан","t":"Спорт","l":"https://t.me/qazpreml2"},
{"name":"Әдіс-тәсілдер Шолпан Тохбергенқызынан","handle":"adistasilder","s":9616,"v":1600,"c":"Казахстан","t":"Общие","l":"https://t.me/adistasilder"},
{"name":"HISTORICA | ҰБТ-2026","handle":"history_alibek","s":9589,"v":1700,"c":"Казахстан","t":"Общие","l":"https://t.me/history_alibek"},
{"name":"📢 Возможности 🚀 startup-course.com 💰","handle":"startup_course_com","s":9560,"v":1300,"c":"Казахстан","t":"Общие","l":"https://t.me/startup_course_com"},
{"name":"Kolesa.kz","handle":"kolesakz_official","s":9521,"v":5800,"c":"Казахстан","t":"Общие","l":"https://t.me/kolesakz_official"},
{"name":"Голассо!","handle":"golassokz","s":9487,"v":1100,"c":"Казахстан","t":"Общие","l":"https://t.me/golassokz"},
{"name":"ПЕДФОРУМ КАЗАХСТАНА","handle":"pedforum","s":9396,"v":1000,"c":"Казахстан","t":"Общие","l":"https://t.me/pedforum"},
{"name":"Везём из KZ | Доставка из США и Европы","handle":"vezemizkz","s":9382,"v":1400,"c":"Казахстан","t":"Общие","l":"https://t.me/vezemizkz"},
{"name":"🎙️Dop_d0malak","handle":"dop_d0malak","s":9320,"v":2100,"c":"Казахстан","t":"Общие","l":"https://t.me/dop_d0malak"},
{"name":"Internship ME","handle":"huntmeinternship","s":9262,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/huntmeinternship"},
{"name":"ҚАЗАҚСТАН ҰСТАЗДАРЫ","handle":"biliminsider","s":9175,"v":1200,"c":"Казахстан","t":"Образование","l":"https://t.me/biliminsider"},
{"name":"Мектепке дейінгі ұйым педагогтары","handle":"rcdd_pedagogiDO","s":9141,"v":1900,"c":"Казахстан","t":"Еда/Досуг","l":"https://t.me/rcdd_pedagogiDO"},
{"name":"Жасанды Интеллект | kano_neiro","handle":"kano_neiro","s":9089,"v":1500,"c":"Казахстан","t":"Общие","l":"https://t.me/kano_neiro"},
{"name":"Қазақстан Тарихы 2026","handle":"qazaqstantarixz","s":9060,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/qazaqstantarixz"},
{"name":"FARABI UNIVERSITY","handle":"kaznu34","s":9036,"v":242,"c":"Казахстан","t":"Общие","l":"https://t.me/kaznu34"},
{"name":"НАУРЫЗ ҰБТ/ЕНТ 2026. | KEREKнама.","handle":"kereknamammen140","s":8973,"v":2500,"c":"Казахстан","t":"Общие","l":"https://t.me/kereknamammen140"},
{"name":"БИОЛОГИЯ| ҰБТ 2026","handle":"biologya_ubt_kz","s":8858,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/biologya_ubt_kz"},
{"name":"ALYPSOQ","handle":"alypsoq","s":8721,"v":2900,"c":"Казахстан","t":"Общие","l":"https://t.me/alypsoq"},
{"name":"SHANTAL | нижнее белье ОПТОМ","handle":"Shantallingerieopt","s":8706,"v":942,"c":"Казахстан","t":"Общие","l":"https://t.me/Shantallingerieopt"},
{"name":"Kórgizbe qurallar","handle":"korgizbequrallar","s":8666,"v":6100,"c":"Казахстан","t":"Общие","l":"https://t.me/korgizbequrallar"},
{"name":"Жаңашыл педагог👩‍🏫👨‍🏫/ Әдіс-тәсілдер📑","handle":"kornekiliiik","s":8576,"v":295,"c":"Казахстан","t":"Еда/Досуг","l":"https://t.me/kornekiliiik"},
{"name":"ЖАҢАШЫЛ ҰСТАЗ👩🏼‍💼","handle":"zhanashylustaz07","s":8564,"v":209,"c":"Казахстан","t":"Общие","l":"https://t.me/zhanashylustaz07"},
{"name":"Тусипбекова Шолпан","handle":"SholpanTussipbekova","s":8482,"v":1300,"c":"Казахстан","t":"Общие","l":"https://t.me/SholpanTussipbekova"},
{"name":"ҚазМұнайГаз / КазМунайГаз","handle":"kmgpress","s":8403,"v":1800,"c":"Казахстан","t":"Новостные","l":"https://t.me/kmgpress"},
{"name":"География.kz","handle":"geografia_kz","s":8280,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/geografia_kz"},
{"name":"Vesti.kz - Новости спорта","handle":"vestisport","s":8197,"v":1600,"c":"Казахстан","t":"Новостные","l":"https://t.me/vestisport"},
{"name":"SAT SPACE 🚀","handle":"SAT_SPACE","s":8148,"v":2100,"c":"Казахстан","t":"Общие","l":"https://t.me/SAT_SPACE"},
{"name":"Мұғалімдерге арналған Республикалық порталы🇰🇿","handle":"bbilimjoly","s":8140,"v":665,"c":"Казахстан","t":"Образование","l":"https://t.me/bbilimjoly"},
{"name":"Mystart 🏁","handle":"mystartkz","s":8096,"v":3600,"c":"Казахстан","t":"Общие","l":"https://t.me/mystartkz"},
{"name":"Temirbek Academy","handle":"temirbekeducation","s":7891,"v":657,"c":"Казахстан","t":"Образование","l":"https://t.me/temirbekeducation"},
{"name":"Qazaq.education | 2026","handle":"qazaqeducation","s":7754,"v":550,"c":"Казахстан","t":"Образование","l":"https://t.me/qazaqeducation"},
{"name":"Школа Практикующего Бухгалтера \"Коломейцева-инфо\"","handle":"kolomeitsevaschool","s":7497,"v":1300,"c":"Казахстан","t":"Общие","l":"https://t.me/kolomeitsevaschool"},
{"name":"Punch KZ | Новости спорта и мира ММА","handle":"sportskazak","s":7447,"v":1100,"c":"Казахстан","t":"Новостные","l":"https://t.me/sportskazak"},
{"name":"Kazakhstan Judo Team","handle":"kazjudoteam","s":7416,"v":2800,"c":"Казахстан","t":"Общие","l":"https://t.me/kazjudoteam"},
{"name":"ТАРИХ және ҚҰҚЫҚ НЕГІЗДЕРІ САБАҚТА ЖӘНЕ САБАҚТАН ТЫС","handle":"tarichC","s":7385,"v":2000,"c":"Казахстан","t":"Общие","l":"https://t.me/tarichC"},
{"name":"Всё о стройке Казахстана","handle":"vse_o_strojke_SNG","s":7217,"v":2600,"c":"Казахстан","t":"Общие","l":"https://t.me/vse_o_strojke_SNG"},
{"name":"ӘЙ, СТУДЕНТ?","handle":"aistudentTOP","s":7212,"v":1500,"c":"Казахстан","t":"Общие","l":"https://t.me/aistudentTOP"},
{"name":"iKapitalist","handle":"ikapitalist","s":7172,"v":2400,"c":"Казахстан","t":"Общие","l":"https://t.me/ikapitalist"},
{"name":"TransExpert.kz","handle":"transExpert01kz","s":7145,"v":62,"c":"Казахстан","t":"Общие","l":"https://t.me/transExpert01kz"},
{"name":"Биология 🔬 Әдемі Қанатқызымен 👩","handle":"biologywithademi","s":7117,"v":2100,"c":"Казахстан","t":"Общие","l":"https://t.me/biologywithademi"},
{"name":"Elena_Dmitry","handle":"deokz","s":6951,"v":5800,"c":"Казахстан","t":"Общие","l":"https://t.me/deokz"},
{"name":"Teez Сатушылары / Продавцы Teez","handle":"teezkz_seller","s":6894,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/teezkz_seller"},
{"name":"Бизнес Алматы | Business Almaty","handle":"biznesshtabalmaty","s":6811,"v":779,"c":"Алматы","t":"Бизнес","l":"https://t.me/biznesshtabalmaty"},
{"name":"DOP | Доп","handle":"dopfutbol","s":6786,"v":1100,"c":"Казахстан","t":"Общие","l":"https://t.me/dopfutbol"},
{"name":"Дядя Ваня","handle":"uncle_Vanja","s":6762,"v":1100,"c":"Казахстан","t":"Общие","l":"https://t.me/uncle_Vanja"},
{"name":"НАУРЫЗ ҰБТ | 2026","handle":"ubt2026jyl","s":6693,"v":2100,"c":"Казахстан","t":"Общие","l":"https://t.me/ubt2026jyl"},
{"name":"ДЖТ| ҰБТ 2026","handle":"dzht_ubt","s":6686,"v":1400,"c":"Казахстан","t":"Общие","l":"https://t.me/dzht_ubt"},
{"name":"Magnum.kz","handle":"magnum","s":6685,"v":1100,"c":"Казахстан","t":"Общие","l":"https://t.me/magnum"},
{"name":"Astana Press📑","handle":"astana_press","s":6636,"v":606,"c":"Астана","t":"Новостные","l":"https://t.me/astana_press"},
{"name":"ПРОкатит","handle":"prokatit_kz","s":6586,"v":2000,"c":"Казахстан","t":"Общие","l":"https://t.me/prokatit_kz"},
{"name":"g_mektep_2_сынып","handle":"gmektep","s":6488,"v":2400,"c":"Казахстан","t":"Общие","l":"https://t.me/gmektep"},
{"name":"OFF SIDE | FOOTBALL","handle":"offsidefootballkz","s":6453,"v":268,"c":"Казахстан","t":"Спорт","l":"https://t.me/offsidefootballkz"},
{"name":"My Extra","handle":"myextrakz","s":6414,"v":1500,"c":"Казахстан","t":"Общие","l":"https://t.me/myextrakz"},
{"name":"ҰБТ МАТЕМАТИКА || Мөлдір Әділқызы","handle":"moldir_adilkyzy","s":6410,"v":540,"c":"Казахстан","t":"Общие","l":"https://t.me/moldir_adilkyzy"},
{"name":"qaztrend","handle":"qaztrend","s":6385,"v":353,"c":"Казахстан","t":"Общие","l":"https://t.me/qaztrend"},
{"name":"Атамекен - Қазақстан Республикасының Ұлттық кәсіпкерлер палатасы","handle":"Atamekennews","s":6333,"v":237,"c":"Казахстан","t":"Новостные","l":"https://t.me/Atamekennews"},
{"name":"HELLO HR ВАКАНСИЯ КАНАЛЫ","handle":"kzfreelance","s":6148,"v":708,"c":"Казахстан","t":"Общие","l":"https://t.me/kzfreelance"},
{"name":"OSports Live","handle":"osports_live","s":6133,"v":8400,"c":"Казахстан","t":"Спорт","l":"https://t.me/osports_live"},
{"name":"STEEL.D","handle":"steelDida","s":6133,"v":3300,"c":"Казахстан","t":"Общие","l":"https://t.me/steelDida"},
{"name":"Работа в Казахстане | Алматы","handle":"podrabotka_vakansii_it","s":6109,"v":930,"c":"Алматы","t":"Общие","l":"https://t.me/podrabotka_vakansii_it"},
{"name":"ҚАЗАҚСТАН ТАРИХЫ | ҰБТ | САЯН АҒАЙ","handle":"sayan_history","s":6106,"v":3000,"c":"Казахстан","t":"Общие","l":"https://t.me/sayan_history"},
{"name":"Prosports.kz","handle":"prosports_kz","s":6095,"v":2000,"c":"Казахстан","t":"Спорт","l":"https://t.me/prosports_kz"},
{"name":"Футзал Казахстан 🇰🇿","handle":"futsalkazakhstan","s":6078,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/futsalkazakhstan"},
{"name":"Гастробайтер","handle":"Gastrobiterkz","s":6053,"v":1600,"c":"Казахстан","t":"Общие","l":"https://t.me/Gastrobiterkz"},
{"name":"BSN","handle":"sunwoonews","s":5900,"v":5800,"c":"Казахстан","t":"Новостные","l":"https://t.me/sunwoonews"},
{"name":"ЕНТ 2026 | result","handle":"entresult","s":5894,"v":1900,"c":"Казахстан","t":"Общие","l":"https://t.me/entresult"},
{"name":"mou667","handle":"moucsgo","s":5853,"v":880,"c":"Казахстан","t":"Общие","l":"https://t.me/moucsgo"},
{"name":"ҰБТ 2026 СЛИВЫ","handle":"ubt_slivs","s":5843,"v":535,"c":"Казахстан","t":"Общие","l":"https://t.me/ubt_slivs"},
{"name":"UTest — ЕНТ 2026","handle":"utest_kz","s":5796,"v":4000,"c":"Казахстан","t":"Образование","l":"https://t.me/utest_kz"},
{"name":"МАТЕМАТИКА | ҰБТ ЛАЙФХАК","handle":"xakmat","s":5775,"v":2100,"c":"Казахстан","t":"Общие","l":"https://t.me/xakmat"},
{"name":"Серый CARDINAL🇰🇿⚽️","handle":"seryicard","s":5670,"v":3100,"c":"Казахстан","t":"Общие","l":"https://t.me/seryicard"},
{"name":"Almaty Marathon","handle":"almaty_marathon","s":5664,"v":2200,"c":"Алматы","t":"Общие","l":"https://t.me/almaty_marathon"},
{"name":"Ақбота Болатқызы","handle":"rabotaaktauzhumys","s":5599,"v":754,"c":"Актау","t":"Общие","l":"https://t.me/rabotaaktauzhumys"},
{"name":"ҰБТ СЛИВ | 2026","handle":"ubtent26","s":5535,"v":690,"c":"Казахстан","t":"Общие","l":"https://t.me/ubtent26"},
{"name":"Aidyn Kozhakhmet","handle":"Kozhakhmet_inside_official","s":5507,"v":3400,"c":"Казахстан","t":"Общие","l":"https://t.me/Kozhakhmet_inside_official"},
{"name":"Алтынсарин академиясы","handle":"ubaedukz","s":5502,"v":835,"c":"Казахстан","t":"Общие","l":"https://t.me/ubaedukz"},
{"name":"Auto News KZ","handle":"auto_news_kz","s":5494,"v":1200,"c":"Казахстан","t":"Новостные","l":"https://t.me/auto_news_kz"},
{"name":"БАРСЕЛОНА | QAZAQSTAN","handle":"fcb_qazaq","s":5477,"v":2100,"c":"Казахстан","t":"Общие","l":"https://t.me/fcb_qazaq"},
{"name":"MARQAR OFFICIAL","handle":"marqarofficial","s":5363,"v":5200,"c":"Казахстан","t":"Общие","l":"https://t.me/marqarofficial"},
{"name":"Магистратура с Enhelp_kz 🎓🍀","handle":"enhelp_kz","s":5151,"v":1000,"c":"Казахстан","t":"Общие","l":"https://t.me/enhelp_kz"},
{"name":"Kazakhstan Boxing Federation","handle":"boxing_kazakhstan","s":5150,"v":1300,"c":"Казахстан","t":"Общие","l":"https://t.me/boxing_kazakhstan"},
{"name":"ИНФОРМАТИКА | ҰБТ | JUZ40","handle":"amazingteaminfoo","s":5105,"v":1100,"c":"Казахстан","t":"Общие","l":"https://t.me/amazingteaminfoo"},
{"name":"«Вкус Жизни: рецепты успеха","handle":"vkus_zhiz","s":5102,"v":418,"c":"Казахстан","t":"Еда/Досуг","l":"https://t.me/vkus_zhiz"},
{"name":"Залоговые Авто | Проблемные","handle":"Auto_Kazahstan","s":5081,"v":1100,"c":"Казахстан","t":"Авто","l":"https://t.me/Auto_Kazahstan"},
{"name":"Candidate Kairov","handle":"kairov_candidate","s":5064,"v":2000,"c":"Казахстан","t":"Общие","l":"https://t.me/kairov_candidate"},
{"name":"ТРЕБУЮТСЯ УЧИТЕЛЯ🇰🇿","handle":"van_bilim","s":4991,"v":398,"c":"Казахстан","t":"Образование","l":"https://t.me/van_bilim"},
{"name":"КАТАЛОГ авто из США - Grand Car Казахстан","handle":"grandcarusa","s":4989,"v":493,"c":"Казахстан","t":"Авто","l":"https://t.me/grandcarusa"},
{"name":"ФИЗИКА пәні МАТЕРИАЛДАРЫ","handle":"fizikamaterialdar","s":4941,"v":2700,"c":"Казахстан","t":"Общие","l":"https://t.me/fizikamaterialdar"},
{"name":"Олжас ағайдың детилері🫶","handle":"olzhasagaidetileri","s":4892,"v":2500,"c":"Казахстан","t":"Общие","l":"https://t.me/olzhasagaidetileri"},
{"name":"BI Group","handle":"bidevelopment","s":4871,"v":1300,"c":"Казахстан","t":"Общие","l":"https://t.me/bidevelopment"},
{"name":"CineleKZ веломаркет","handle":"cinelekz","s":4853,"v":730,"c":"Казахстан","t":"Общие","l":"https://t.me/cinelekz"},
{"name":"Алишер Бейсебай | Gaming","handle":"alishsmod","s":4742,"v":977,"c":"Казахстан","t":"Общие","l":"https://t.me/alishsmod"},
{"name":"BlauGrana Vibes News | Барселона","handle":"BlaugranaVibesNews","s":4583,"v":1300,"c":"Казахстан","t":"Новостные","l":"https://t.me/BlaugranaVibesNews"},
{"name":"Бухонин - Маркетплейсы и продажи","handle":"bukhonin_artem","s":4283,"v":916,"c":"Казахстан","t":"Общие","l":"https://t.me/bukhonin_artem"},
{"name":"Просто и Вкусно","handle":"prostoivkusno_137","s":4171,"v":409,"c":"Казахстан","t":"Общие","l":"https://t.me/prostoivkusno_137"},
{"name":"Kaz_wrestling 🇰🇿","handle":"kazwrestlinggg","s":4160,"v":2700,"c":"Казахстан","t":"Общие","l":"https://t.me/kazwrestlinggg"},
{"name":"Инсайды волейбол KZ","handle":"insaidkazvolley","s":4078,"v":2200,"c":"Казахстан","t":"Общие","l":"https://t.me/insaidkazvolley"},
{"name":"Личный Капитал 💰","handle":"kapitaldar","s":3971,"v":290,"c":"Казахстан","t":"Общие","l":"https://t.me/kapitaldar"},
{"name":"BAIPKET","handle":"baipketw","s":3967,"v":870,"c":"Казахстан","t":"Общие","l":"https://t.me/baipketw"},
{"name":"Qsport Qazaqstan","handle":"qsportqazaqstan","s":3896,"v":481,"c":"Казахстан","t":"Спорт","l":"https://t.me/qsportqazaqstan"},
{"name":"«Ордабасы» ФК | Ordabasy FC","handle":"ordabasyfc","s":3857,"v":1100,"c":"Казахстан","t":"Новостные","l":"https://t.me/ordabasyfc"},
{"name":"Продажа Фуры Казакстан 🇰🇿🚛","handle":"prodaja_fura","s":3788,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/prodaja_fura"},
{"name":"KFF LEAGUE","handle":"kffleague","s":3748,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/kffleague"},
{"name":"КГА 🇰🇿","handle":"caa_kaz","s":3551,"v":1000,"c":"Казахстан","t":"Общие","l":"https://t.me/caa_kaz"},
{"name":"Almaty_Joly","handle":"AlmatyJoly","s":3544,"v":1300,"c":"Алматы","t":"Общие","l":"https://t.me/AlmatyJoly"},
{"name":"🇰🇿Real Madrid / Hala Madrid","handle":"realmadridqazaqstan","s":3495,"v":742,"c":"Казахстан","t":"Общие","l":"https://t.me/realmadridqazaqstan"},
{"name":"Official | MELBET KZ 🇰🇿","handle":"melbet_KZT","s":3471,"v":507,"c":"Казахстан","t":"Общие","l":"https://t.me/melbet_KZT"},
{"name":"UGC Match | микроблогеры | блогеры | Казахстан","handle":"ugcmatch","s":3467,"v":1500,"c":"Казахстан","t":"Общие","l":"https://t.me/ugcmatch"},
{"name":"Gameroom Football","handle":"gameroom_football","s":3316,"v":737,"c":"Казахстан","t":"Спорт","l":"https://t.me/gameroom_football"},
{"name":"Qazaqstan Olympic team","handle":"olympickz","s":3287,"v":624,"c":"Казахстан","t":"Общие","l":"https://t.me/olympickz"},
{"name":"Че гуглит татар кызы","handle":"cheguglittatarkyzy","s":3258,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/cheguglittatarkyzy"},
{"name":"ALASH SPORTY","handle":"alashsporty","s":3248,"v":991,"c":"Казахстан","t":"Спорт","l":"https://t.me/alashsporty"},
{"name":"Гол емес! ⚽️❌","handle":"goal_emes","s":3205,"v":1700,"c":"Казахстан","t":"Спорт","l":"https://t.me/goal_emes"},
{"name":"FC Aktobe","handle":"fc_aktobe","s":3197,"v":1400,"c":"Актобе","t":"Общие","l":"https://t.me/fc_aktobe"},
{"name":"𝟷𝟸","handle":"ahdbcldn","s":3143,"v":74,"c":"Казахстан","t":"Общие","l":"https://t.me/ahdbcldn"},
{"name":"Oralgazin","handle":"Oralgazin","s":3135,"v":410,"c":"Уральск","t":"Общие","l":"https://t.me/Oralgazin"},
{"name":"Солай де | UFC 🥊","handle":"solaideufc","s":2888,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/solaideufc"},
{"name":"«ЕЛІМАЙ» ФК | FC «ELIMAI»","handle":"fc_elimai","s":2884,"v":822,"c":"Казахстан","t":"Общие","l":"https://t.me/fc_elimai"},
{"name":"Coca-Cola Belesteri","handle":"cocacolabelesteri","s":2814,"v":663,"c":"Казахстан","t":"Общие","l":"https://t.me/cocacolabelesteri"},
{"name":"Baipket: Маркетинг","handle":"baipmarketing","s":2795,"v":655,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/baipmarketing"},
{"name":"🌸Казахские шрифты🌸","handle":"shriftykaz","s":2749,"v":839,"c":"Казахстан","t":"Общие","l":"https://t.me/shriftykaz"},
{"name":"vi improved","handle":"theneovim","s":2744,"v":477,"c":"Казахстан","t":"Общие","l":"https://t.me/theneovim"},
{"name":"Ozon Marketplace Kazakhstan","handle":"ozonkazakhstan","s":2584,"v":330,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/ozonkazakhstan"},
{"name":"ASTANA TRIATHLON","handle":"astanatriathlon","s":2563,"v":1300,"c":"Астана","t":"Общие","l":"https://t.me/astanatriathlon"},
{"name":"THA Info","handle":"THA_Info","s":2505,"v":720,"c":"Казахстан","t":"Общие","l":"https://t.me/THA_Info"},
{"name":"FlyArystan info","handle":"flyarystan_inform","s":2466,"v":786,"c":"Казахстан","t":"Общие","l":"https://t.me/flyarystan_inform"},
{"name":"Дикая Пуля | ФК Кайрат","handle":"dikayapulya","s":2449,"v":313,"c":"Казахстан","t":"Общие","l":"https://t.me/dikayapulya"},
{"name":"Beksports.kz","handle":"beksportkz","s":2446,"v":582,"c":"Казахстан","t":"Спорт","l":"https://t.me/beksportkz"},
{"name":"🚘 CARS MARKET","handle":"qiche_kz","s":2420,"v":611,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/qiche_kz"},
{"name":"Aladop","handle":"aladopkz","s":2314,"v":371,"c":"Казахстан","t":"Общие","l":"https://t.me/aladopkz"},
{"name":"Héctor Fort García","handle":"hctorforrt39","s":2299,"v":839,"c":"Казахстан","t":"Общие","l":"https://t.me/hctorforrt39"},
{"name":"Олимпиада Казахстан | Milano Cortina-2026","handle":"sport_2026_kaz","s":2266,"v":674,"c":"Казахстан","t":"Спорт","l":"https://t.me/sport_2026_kaz"},
{"name":"Асқарбиновая Орда","handle":"askar4308","s":2252,"v":828,"c":"Казахстан","t":"Общие","l":"https://t.me/askar4308"},
{"name":"AutoReport","handle":"auto_report","s":2244,"v":403,"c":"Казахстан","t":"Авто","l":"https://t.me/auto_report"},
{"name":"PRO KZ SPORT","handle":"prokzsport","s":2211,"v":3400,"c":"Казахстан","t":"Спорт","l":"https://t.me/prokzsport"},
{"name":"90min | FOOTBALL","handle":"footballkz90","s":2195,"v":262,"c":"Казахстан","t":"Спорт","l":"https://t.me/footballkz90"},
{"name":"Дала Қырандары","handle":"qyrandary","s":2181,"v":776,"c":"Казахстан","t":"Общие","l":"https://t.me/qyrandary"},
{"name":"🇹🇷ЖЕНСКАЯ ОБУВЬ, НАТУРАЛЬНАЯ КОЖА оптом из Турции.От turk_opt_ing","handle":"WomenShoes_turk_opt_ing","s":2150,"v":23,"c":"Казахстан","t":"Общие","l":"https://t.me/WomenShoes_turk_opt_ing"},
{"name":"📢 Applikata oqıw orayı (MBE)","handle":"Jaqsimurat_matematika_repetitor","s":2146,"v":2100,"c":"Казахстан","t":"Общие","l":"https://t.me/Jaqsimurat_matematika_repetitor"},
{"name":"ТРАБЛШУТЕР.KZ","handle":"biznesbastau","s":2110,"v":155,"c":"Казахстан","t":"Общие","l":"https://t.me/biznesbastau"},
{"name":"Blaugrana Vibes","handle":"Blaugrana_Vibes","s":2097,"v":677,"c":"Казахстан","t":"Общие","l":"https://t.me/Blaugrana_Vibes"},
{"name":"Әйдә ШаяРТ!","handle":"aydashayart","s":2093,"v":753,"c":"Казахстан","t":"Общие","l":"https://t.me/aydashayart"},
{"name":"Trans_info_kz - новости в сфере грузоперевозок (логистика, перевозки, дозволы, допуски)","handle":"trans_info_kz","s":2084,"v":1000,"c":"Казахстан","t":"Новостные","l":"https://t.me/trans_info_kz"},
{"name":"Telephone of Kazakhstan 🇰🇿","handle":"KozTiedi","s":2076,"v":599,"c":"Казахстан","t":"Общие","l":"https://t.me/KozTiedi"},
{"name":"My Rocket Science","handle":"myrocketscience","s":2060,"v":824,"c":"Казахстан","t":"Общие","l":"https://t.me/myrocketscience"},
{"name":"Culture Qazaqstan🇰🇿","handle":"culture_qazaqstan_channel","s":2055,"v":1800,"c":"Казахстан","t":"Общие","l":"https://t.me/culture_qazaqstan_channel"},
{"name":"ВОЗВРАТ НАЛОГОВ ИЗ АНГЛИИ UK | WHITE TAX RETURNS","handle":"whitetax_returns","s":2012,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/whitetax_returns"},
{"name":"Sportilinet.kz | Спорт Шредингера","handle":"sportilinetkz","s":2009,"v":257,"c":"Казахстан","t":"Спорт","l":"https://t.me/sportilinetkz"},
{"name":"СпортNUR","handle":"sportnurkz","s":1976,"v":4200,"c":"Казахстан","t":"Спорт","l":"https://t.me/sportnurkz"},
{"name":"Пардашьян","handle":"pardashian","s":1967,"v":532,"c":"Казахстан","t":"Общие","l":"https://t.me/pardashian"},
{"name":"мой хуй бледный как ленин железный как сталин","handle":"subject282","s":1962,"v":673,"c":"Казахстан","t":"Общие","l":"https://t.me/subject282"},
{"name":"Kazakhstan Taekwondo WT","handle":"qaztkd","s":1949,"v":912,"c":"Казахстан","t":"Общие","l":"https://t.me/qaztkd"},
{"name":"МПН | Маркетинг Последней Надежды","handle":"marketingpn","s":1943,"v":417,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/marketingpn"},
{"name":"May Food Bless You","handle":"mayfoodblessyou","s":1913,"v":1000,"c":"Казахстан","t":"Еда/Досуг","l":"https://t.me/mayfoodblessyou"},
{"name":"Conditinho clips🫆","handle":"conditinhoclips","s":1912,"v":415,"c":"Казахстан","t":"Общие","l":"https://t.me/conditinhoclips"},
{"name":"рамиз.txt","handle":"ramiz_txt","s":1907,"v":810,"c":"Казахстан","t":"Общие","l":"https://t.me/ramiz_txt"},
{"name":"Карго 878 PRO 💎 Купоны , ссылки на товар Пиндоудо , ТАОБАО , 1688 , Пойзон","handle":"cargo878pinduoduo","s":1903,"v":401,"c":"Казахстан","t":"Общие","l":"https://t.me/cargo878pinduoduo"},
{"name":"Союз строителей Казахстана","handle":"kzbuilders","s":1891,"v":377,"c":"Казахстан","t":"Общие","l":"https://t.me/kzbuilders"},
{"name":"ҚУАТТЫҢ ЖҰДЫРЫҒЫ👊","handle":"kuat_goat","s":1862,"v":465,"c":"Казахстан","t":"Общие","l":"https://t.me/kuat_goat"},
{"name":"NomadApc про Ютуб 🇺🇲","handle":"arsensway","s":1838,"v":1200,"c":"Казахстан","t":"Общие","l":"https://t.me/arsensway"},
{"name":"AUTOFERMA","handle":"autoferma_LLC","s":1829,"v":427,"c":"Казахстан","t":"Авто","l":"https://t.me/autoferma_LLC"},
{"name":"BARCELONA | QAZAQSTAN","handle":"fcbqaz","s":1801,"v":1000,"c":"Казахстан","t":"Общие","l":"https://t.me/fcbqaz"},
{"name":"Finnews.kz","handle":"finnewskz","s":1776,"v":556,"c":"Казахстан","t":"Новостные","l":"https://t.me/finnewskz"},
{"name":"Satu.kz для предпринимателей","handle":"satubusiness","s":1766,"v":466,"c":"Казахстан","t":"Бизнес","l":"https://t.me/satubusiness"},
{"name":"Китайские автомобили / KZ / Казахстан","handle":"autochinakz","s":1747,"v":623,"c":"Казахстан","t":"Авто","l":"https://t.me/autochinakz"},
{"name":"TAXI KOLESA","handle":"taxikolesa","s":1724,"v":333,"c":"Казахстан","t":"Общие","l":"https://t.me/taxikolesa"},
{"name":"Бәке, не хабар? 🚀","handle":"bakytbay","s":1721,"v":270,"c":"Казахстан","t":"Общие","l":"https://t.me/bakytbay"},
{"name":"Анонимка","handle":"aitufmanon","s":1703,"v":316,"c":"Казахстан","t":"Общие","l":"https://t.me/aitufmanon"},
{"name":"ITalent KZ","handle":"italent_kz","s":1687,"v":3,"c":"Казахстан","t":"Общие","l":"https://t.me/italent_kz"},
{"name":"Запчасттер","handle":"beymalimoto","s":1662,"v":3600,"c":"Казахстан","t":"Общие","l":"https://t.me/beymalimoto"},
{"name":"Kia Qazaqstan","handle":"kiaqazaqstan","s":1636,"v":1100,"c":"Казахстан","t":"Общие","l":"https://t.me/kiaqazaqstan"},
{"name":"AZAMAT SPORT","handle":"azamatsportkz","s":1593,"v":1100,"c":"Казахстан","t":"Спорт","l":"https://t.me/azamatsportkz"},
{"name":"Адмет Акхтер 🇰🇿🇸🇬 — IT-бизнес, продукты и цифровизация","handle":"admet_akhter","s":1572,"v":325,"c":"Казахстан","t":"Бизнес","l":"https://t.me/admet_akhter"},
{"name":"Луна карго Алматы","handle":"lunakargo","s":1532,"v":626,"c":"Алматы","t":"Общие","l":"https://t.me/lunakargo"},
{"name":"Спорт елі","handle":"sport_eli_KZ","s":1500,"v":104,"c":"Казахстан","t":"Спорт","l":"https://t.me/sport_eli_KZ"},
{"name":"1XDODA","handle":"doda1x","s":1469,"v":1400,"c":"Казахстан","t":"Общие","l":"https://t.me/doda1x"},
{"name":"Satarman.com | Умные продажи","handle":"kubeyevcom","s":1457,"v":144,"c":"Казахстан","t":"Общие","l":"https://t.me/kubeyevcom"},
{"name":"City Transportation Systems","handle":"citytrasportationsystems","s":1445,"v":539,"c":"Казахстан","t":"Спорт","l":"https://t.me/citytrasportationsystems"},
{"name":"Anon Shymkent | Анонимка Шымкента","handle":"anon_shym","s":1440,"v":1000,"c":"Шымкент","t":"Общие","l":"https://t.me/anon_shym"},
{"name":"📝Kazakh_football_inside","handle":"kazakh_football_inside","s":1431,"v":1100,"c":"Казахстан","t":"Спорт","l":"https://t.me/kazakh_football_inside"},
{"name":"‼️ 21Auto - доставка АВТО","handle":"auto21kz","s":1430,"v":709,"c":"Казахстан","t":"Авто","l":"https://t.me/auto21kz"},
{"name":"ҰЗЫН ҚҰЛАҚ","handle":"uzynqulaq_official","s":1429,"v":1300,"c":"Казахстан","t":"Общие","l":"https://t.me/uzynqulaq_official"},
{"name":"DIGITAL SMM | СММ ВАКАНСИИ КАЗАХСТАН","handle":"qazdigitall","s":1410,"v":319,"c":"Казахстан","t":"Общие","l":"https://t.me/qazdigitall"},
{"name":"Анна в Телеграм🔺ПРОДВИЖЕНИЕ соцсетей","handle":"offer_anna","s":1336,"v":90,"c":"Казахстан","t":"Общие","l":"https://t.me/offer_anna"},
{"name":"NS Textile Домашний текстиль из Турции","handle":"ns_textile_kz","s":1325,"v":189,"c":"Казахстан","t":"Общие","l":"https://t.me/ns_textile_kz"},
{"name":"@prodashy","handle":"loopsbyashy","s":1313,"v":741,"c":"Казахстан","t":"Общие","l":"https://t.me/loopsbyashy"},
{"name":"ҚАЗАҚША ӘЗІЛ | АНЕКДОТТАР | МЕМДЕР | STAND UP","handle":"kazakhsmile","s":1288,"v":266,"c":"Казахстан","t":"Общие","l":"https://t.me/kazakhsmile"},
{"name":"Алмаз Зиатдинов","handle":"almaz_ziatdinov","s":1262,"v":538,"c":"Казахстан","t":"Общие","l":"https://t.me/almaz_ziatdinov"},
{"name":"Айнұр Жеңісбекқызы","handle":"ainurzhenisbekk","s":1246,"v":142,"c":"Казахстан","t":"Общие","l":"https://t.me/ainurzhenisbekk"},
{"name":"Делаем или нет","handle":"krinzmarketing","s":1241,"v":584,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/krinzmarketing"},
{"name":"®Бизнес с dōTERRA Казахстан","handle":"doterrabusinesskz","s":1190,"v":392,"c":"Казахстан","t":"Бизнес","l":"https://t.me/doterrabusinesskz"},
{"name":"PR room","handle":"PRroomkz","s":1189,"v":264,"c":"Казахстан","t":"Общие","l":"https://t.me/PRroomkz"},
{"name":"Homsters - приложение по недвижимости","handle":"homsterskz","s":1176,"v":147,"c":"Казахстан","t":"Недвижимость","l":"https://t.me/homsterskz"},
{"name":"PR alliance🌍🤝","handle":"PRalliance","s":1173,"v":440,"c":"Казахстан","t":"Общие","l":"https://t.me/PRalliance"},
{"name":"Азевич про масштаб бизнеса","handle":"azevichcommunity","s":1171,"v":371,"c":"Казахстан","t":"Бизнес","l":"https://t.me/azevichcommunity"},
{"name":"Солнцемобили Альтернативные источники энергии Гонка Солнцемобилей по Казахстану","handle":"sunmobile","s":1167,"v":599,"c":"Казахстан","t":"Общие","l":"https://t.me/sunmobile"},
{"name":"Likhtman thinks","handle":"prandmore","s":1162,"v":329,"c":"Казахстан","t":"Общие","l":"https://t.me/prandmore"},
{"name":"DODO PIZZA AKTOBE","handle":"dodopizzzaaktobe","s":1125,"v":509,"c":"Актобе","t":"Общие","l":"https://t.me/dodopizzzaaktobe"},
{"name":"NQZ - ASTANA INTERNATIONAL AIRPORT","handle":"nqzairport","s":1122,"v":564,"c":"Астана","t":"Общие","l":"https://t.me/nqzairport"},
{"name":"HeadSomm","handle":"headsomm","s":1083,"v":317,"c":"Казахстан","t":"Общие","l":"https://t.me/headsomm"},
{"name":"Kazakhpress","handle":"kazakhpress","s":1070,"v":123,"c":"Казахстан","t":"Новостные","l":"https://t.me/kazakhpress"},
{"name":"ARFC","handle":"arfckz","s":1068,"v":279,"c":"Казахстан","t":"Общие","l":"https://t.me/arfckz"},
{"name":"Yapartner Яндекс.Такси Казахстан","handle":"Yapartnerkz","s":1057,"v":241,"c":"Казахстан","t":"Общие","l":"https://t.me/Yapartnerkz"},
{"name":"Astana Motors","handle":"AstanaMotorsKz","s":1047,"v":459,"c":"Астана","t":"Общие","l":"https://t.me/AstanaMotorsKz"},
{"name":"bella’s diary // wayv","handle":"wayv_bellas_diary","s":1041,"v":296,"c":"Казахстан","t":"Общие","l":"https://t.me/wayv_bellas_diary"},
{"name":"RateHawk. CIS","handle":"ratehawkcis","s":1029,"v":499,"c":"Казахстан","t":"Общие","l":"https://t.me/ratehawkcis"},
{"name":"seagulls in love 𐤀","handle":"seagulls_vkook","s":1007,"v":378,"c":"Казахстан","t":"Общие","l":"https://t.me/seagulls_vkook"},
{"name":"兩性技巧，恋爱心理、情感婚姻","handle":"liangxingJQ","s":1007,"v":295,"c":"Казахстан","t":"Общие","l":"https://t.me/liangxingJQ"},
{"name":"GEOKURS","handle":"geokurs_kz","s":933,"v":241,"c":"Казахстан","t":"Общие","l":"https://t.me/geokurs_kz"},
{"name":"Turach Community","handle":"turach_community","s":893,"v":454,"c":"Казахстан","t":"Общие","l":"https://t.me/turach_community"},
{"name":"Михаил Ломтадзе","handle":"mikheil_lomtadze","s":891,"v":271,"c":"Казахстан","t":"Общие","l":"https://t.me/mikheil_lomtadze"},
{"name":"Mufid Academy","handle":"Arabtili_Cefr_uz","s":854,"v":492,"c":"Казахстан","t":"Общие","l":"https://t.me/Arabtili_Cefr_uz"},
{"name":"Геннадий Ванин","handle":"gvaninblog","s":843,"v":356,"c":"Казахстан","t":"Общие","l":"https://t.me/gvaninblog"},
{"name":"Турлов купит! Стартапы, cделки и VC в Центральной Азии","handle":"turlov_kupit","s":842,"v":189,"c":"Казахстан","t":"Общие","l":"https://t.me/turlov_kupit"},
{"name":"Карго 878 Шымкент","handle":"shymkentcargo878","s":832,"v":141,"c":"Шымкент","t":"Общие","l":"https://t.me/shymkentcargo878"},
{"name":"Wealth Club","handle":"wealzclub","s":815,"v":90,"c":"Казахстан","t":"Общие","l":"https://t.me/wealzclub"},
{"name":"Marat Shaken LIVE","handle":"ShakenLive","s":797,"v":103,"c":"Казахстан","t":"Общие","l":"https://t.me/ShakenLive"},
{"name":"Недвижка КЗ","handle":"homefinancekz","s":781,"v":845,"c":"Казахстан","t":"Бизнес","l":"https://t.me/homefinancekz"},
{"name":"Ассоциация устойчивого развития территорий Q88","handle":"Association_q88","s":761,"v":49,"c":"Казахстан","t":"Общие","l":"https://t.me/Association_q88"},
{"name":"ALGATOP | Продвижение на KASPI","handle":"AlgaTopKz","s":758,"v":207,"c":"Казахстан","t":"Общие","l":"https://t.me/AlgaTopKz"},
{"name":"Iowa Pro Management","handle":"angryproject","s":722,"v":280,"c":"Казахстан","t":"Общие","l":"https://t.me/angryproject"},
{"name":"KFSA","handle":"nufinance","s":702,"v":1100,"c":"Казахстан","t":"Бизнес","l":"https://t.me/nufinance"},
{"name":"Business FM","handle":"businessfmKZ","s":670,"v":107,"c":"Казахстан","t":"Бизнес","l":"https://t.me/businessfmKZ"},
{"name":"НЕЙРОСЕТИ, маркетинг и мысли \"за жизнь\" от Живого маркетолога","handle":"livemarketer","s":667,"v":336,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/livemarketer"},
{"name":"Яндекс Про для партнёров","handle":"yandexpro_partners","s":661,"v":640,"c":"Казахстан","t":"Общие","l":"https://t.me/yandexpro_partners"},
{"name":"Инвестициялар 🔔🔝","handle":"JurabekBabaev","s":645,"v":118,"c":"Казахстан","t":"Общие","l":"https://t.me/JurabekBabaev"},
{"name":"Fake Detector","handle":"f_detector","s":611,"v":18,"c":"Казахстан","t":"Общие","l":"https://t.me/f_detector"},
{"name":"ACTIVAT VC","handle":"activatvc","s":604,"v":349,"c":"Казахстан","t":"Общие","l":"https://t.me/activatvc"},
{"name":"Commedia KZ","handle":"commediakz","s":595,"v":534,"c":"Казахстан","t":"Общие","l":"https://t.me/commediakz"},
{"name":"NU Case Club Channel","handle":"nu_caseclub","s":579,"v":997,"c":"Казахстан","t":"Общие","l":"https://t.me/nu_caseclub"},
{"name":"iTaxi | Яндекс.Такси","handle":"iTaxi_kz","s":568,"v":168,"c":"Казахстан","t":"Общие","l":"https://t.me/iTaxi_kz"},
{"name":"CREATIWE.kz","handle":"creatiwekz","s":556,"v":231,"c":"Казахстан","t":"Общие","l":"https://t.me/creatiwekz"},
{"name":"Tanika о Китае. Таобао, 1688. Каспи","handle":"tanikaokitae","s":555,"v":62,"c":"Казахстан","t":"Общие","l":"https://t.me/tanikaokitae"},
{"name":"Артюшенко и партнёры","handle":"artandpart","s":549,"v":116,"c":"Казахстан","t":"Общие","l":"https://t.me/artandpart"},
{"name":"Flip Partners","handle":"FlipMarketplaceSellers","s":546,"v":272,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/FlipMarketplaceSellers"},
{"name":"APL GO Информационный канал KZ","handle":"aplgoinfokz","s":544,"v":164,"c":"Казахстан","t":"Общие","l":"https://t.me/aplgoinfokz"},
{"name":"Туризм маркетинг","handle":"marketingtourism","s":543,"v":70,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/marketingtourism"},
{"name":"ITCOMMS - PR guide for IT","handle":"itcomms","s":534,"v":130,"c":"Казахстан","t":"Общие","l":"https://t.me/itcomms"},
{"name":"TEXOL Life","handle":"texolkz","s":522,"v":420,"c":"Казахстан","t":"Общие","l":"https://t.me/texolkz"},
{"name":"Mercedes-benz,ТД AUTOMART, пер.Кобда 2/1,этаж 2,бутик Е8.","handle":"alla_guryeva","s":521,"v":71,"c":"Казахстан","t":"Авто","l":"https://t.me/alla_guryeva"},
{"name":"MEDIA COMMUNITY","handle":"godnyezakazy","s":520,"v":210,"c":"Казахстан","t":"Общие","l":"https://t.me/godnyezakazy"},
{"name":"АвтоКүшті","handle":"autokushti","s":494,"v":75,"c":"Казахстан","t":"Авто","l":"https://t.me/autokushti"},
{"name":"Day of the Toad","handle":"dayofthetoad","s":478,"v":277,"c":"Казахстан","t":"Общие","l":"https://t.me/dayofthetoad"},
{"name":"Digital Events Central Asia","handle":"digital_events_mig","s":478,"v":130,"c":"Казахстан","t":"Общие","l":"https://t.me/digital_events_mig"},
{"name":"ABIS - проверка контрагентов на благонадежность","handle":"kyc_abis","s":475,"v":266,"c":"Казахстан","t":"Общие","l":"https://t.me/kyc_abis"},
{"name":"(с)өзімді түзетейін","handle":"selfcritique","s":447,"v":318,"c":"Казахстан","t":"Общие","l":"https://t.me/selfcritique"},
{"name":"Пиплвотчинг","handle":"peoplewatching_kz","s":441,"v":114,"c":"Казахстан","t":"Общие","l":"https://t.me/peoplewatching_kz"},
{"name":"PENOPLEX_KZ","handle":"penoplex_kz","s":441,"v":627,"c":"Казахстан","t":"Общие","l":"https://t.me/penoplex_kz"},
{"name":"Meet Deadlines","handle":"meetdeadlines","s":418,"v":294,"c":"Казахстан","t":"Общие","l":"https://t.me/meetdeadlines"},
{"name":"Прогрессор ⚡️","handle":"progressorkz","s":406,"v":132,"c":"Казахстан","t":"Общие","l":"https://t.me/progressorkz"},
{"name":"Vitaliy Trenkenshu (Datanomix)","handle":"vitaliytrenkenshu","s":402,"v":390,"c":"Казахстан","t":"Общие","l":"https://t.me/vitaliytrenkenshu"},
{"name":"Арман Жумагалиев: Бизнес и Полиграфия","handle":"Arman_Print_Store","s":401,"v":273,"c":"Казахстан","t":"Бизнес","l":"https://t.me/Arman_Print_Store"},
{"name":"📝Abadan Writes","handle":"abadangani","s":399,"v":44,"c":"Казахстан","t":"Общие","l":"https://t.me/abadangani"},
{"name":"Wine With Kitchi","handle":"winewithkitchi","s":382,"v":82,"c":"Казахстан","t":"Общие","l":"https://t.me/winewithkitchi"},
{"name":"Спонсоры и содержанки Алматы Шымкент","handle":"kzspons3","s":370,"v":162,"c":"Алматы","t":"Общие","l":"https://t.me/kzspons3"},
{"name":"🌍Официальный Канал Разработчика Реал Лайф🌍","handle":"Reallifemod","s":370,"v":107,"c":"Казахстан","t":"Общие","l":"https://t.me/Reallifemod"},
{"name":"Продажа щенки/котята по всему миру","handle":"zooprodam","s":367,"v":110,"c":"Казахстан","t":"Общие","l":"https://t.me/zooprodam"},
{"name":"Работа в Шымкенте | Вакансии | Жұмыс","handle":"rabotka_shymkent","s":366,"v":48,"c":"Шымкент","t":"Общие","l":"https://t.me/rabotka_shymkent"},
{"name":"Заметки цифрового джедая","handle":"jedibizdev","s":359,"v":227,"c":"Казахстан","t":"Еда/Досуг","l":"https://t.me/jedibizdev"},
{"name":"Azamat Kaypanov","handle":"azamatkaypanov","s":350,"v":118,"c":"Казахстан","t":"Общие","l":"https://t.me/azamatkaypanov"},
{"name":"XDS Astana Team","handle":"proteamastana","s":340,"v":188,"c":"Астана","t":"Общие","l":"https://t.me/proteamastana"},
{"name":"TAYNIQ . ДОМ","handle":"luxe_home_channel","s":339,"v":33,"c":"Казахстан","t":"Общие","l":"https://t.me/luxe_home_channel"},
{"name":"Газдай","handle":"Gazdauto","s":333,"v":30,"c":"Казахстан","t":"Авто","l":"https://t.me/Gazdauto"},
{"name":"Мышление предпринимателя","handle":"ABC_Invest_kz","s":330,"v":89,"c":"Казахстан","t":"Общие","l":"https://t.me/ABC_Invest_kz"},
{"name":"Пиархаб в Центральной Азии","handle":"prhubca","s":316,"v":294,"c":"Казахстан","t":"Общие","l":"https://t.me/prhubca"},
{"name":"Tatte.kz","handle":"tattecoffee","s":312,"v":127,"c":"Казахстан","t":"Общие","l":"https://t.me/tattecoffee"},
{"name":"AirMagic-забытая легенда нашего времени!","handle":"airmagic7","s":310,"v":57,"c":"Казахстан","t":"Общие","l":"https://t.me/airmagic7"},
{"name":"Бизнес штаб области Жетісу","handle":"businessshtabalmobl","s":308,"v":16,"c":"Казахстан","t":"Бизнес","l":"https://t.me/businessshtabalmobl"},
{"name":"sleepingnara йомайо","handle":"slpnara","s":307,"v":179,"c":"Казахстан","t":"Общие","l":"https://t.me/slpnara"},
{"name":"Жануарлар әлемі 🐾","handle":"animalwd","s":305,"v":51,"c":"Казахстан","t":"Общие","l":"https://t.me/animalwd"},
{"name":"GWWS #Kazakhstan line 🇰🇿","handle":"gwws_kazhak","s":300,"v":5,"c":"Казахстан","t":"Общие","l":"https://t.me/gwws_kazhak"},
{"name":"Абузы | Схемы заработка | NFT | Crypto | Trading","handle":"shemizarabotkaonlinee","s":299,"v":34,"c":"Казахстан","t":"Общие","l":"https://t.me/shemizarabotkaonlinee"},
{"name":"Купля/Продажа ТОО по всему Казахстану.","handle":"ProdazhaTOOkz","s":298,"v":399,"c":"Казахстан","t":"Общие","l":"https://t.me/ProdazhaTOOkz"},
{"name":"Настя Максименко","handle":"namaksimalkah","s":296,"v":299,"c":"Казахстан","t":"Общие","l":"https://t.me/namaksimalkah"},
{"name":"FitnessData Центральная Азия: Казахстан, Узбекистан, Кыргызстан, Таджикистан","handle":"fitnessdatakz","s":287,"v":117,"c":"Казахстан","t":"Общие","l":"https://t.me/fitnessdatakz"},
{"name":"qara","handle":"qaraproduct","s":282,"v":130,"c":"Казахстан","t":"Общие","l":"https://t.me/qaraproduct"},
{"name":"Реестр КТП и НКТ | Практика и экспертиза |Бизнес | Казахстан 🇰🇿","handle":"reestrktp","s":274,"v":214,"c":"Казахстан","t":"Бизнес","l":"https://t.me/reestrktp"},
{"name":"ОКСАНА КАТЕРИНИЧ 🇵🇼ЛИДЕР SW","handle":"Oksanabiznes","s":263,"v":45,"c":"Казахстан","t":"Общие","l":"https://t.me/Oksanabiznes"},
{"name":"Ержан Терекулов/ТРИЗ для бизнеса","handle":"yerzhan_mindmanager","s":260,"v":72,"c":"Казахстан","t":"Бизнес","l":"https://t.me/yerzhan_mindmanager"},
{"name":"A L I Y A вещает!","handle":"aakhmetovaa","s":259,"v":60,"c":"Казахстан","t":"Общие","l":"https://t.me/aakhmetovaa"},
{"name":"Аннушка про рекламу","handle":"annushka_marketing","s":248,"v":29,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/annushka_marketing"},
{"name":"Авто Казахстан","handle":"auto_qazaqstan","s":247,"v":320,"c":"Казахстан","t":"Авто","l":"https://t.me/auto_qazaqstan"},
{"name":"34 world","handle":"sopeworld34","s":241,"v":119,"c":"Казахстан","t":"Общие","l":"https://t.me/sopeworld34"},
{"name":"Kvadrat⭕️metr","handle":"kvadratometr","s":230,"v":91,"c":"Казахстан","t":"Общие","l":"https://t.me/kvadratometr"},
{"name":"Ttsaterfu","handle":"ttsaterfu","s":227,"v":164,"c":"Казахстан","t":"Общие","l":"https://t.me/ttsaterfu"},
{"name":"Yichang 🐉","handle":"yichang_kz","s":225,"v":129,"c":"Казахстан","t":"Общие","l":"https://t.me/yichang_kz"},
{"name":"Foresight Lab KZ 🇰🇿","handle":"olegmetsik","s":218,"v":48,"c":"Казахстан","t":"Общие","l":"https://t.me/olegmetsik"},
{"name":"pocaxontes.sss","handle":"sssssf13","s":216,"v":358,"c":"Казахстан","t":"Общие","l":"https://t.me/sssssf13"},
{"name":"人情世故|江湖翻译|听言外意|学读心术👂","handle":"gaoxioa","s":207,"v":111,"c":"Казахстан","t":"Общие","l":"https://t.me/gaoxioa"},
{"name":"Қазақстанның Автокөлік Одағы","handle":"kao_kz","s":206,"v":53,"c":"Казахстан","t":"Авто","l":"https://t.me/kao_kz"},
{"name":"my hometerest","handle":"myhometerest","s":196,"v":152,"c":"Казахстан","t":"Общие","l":"https://t.me/myhometerest"},
{"name":"Алматинский Архитектор","handle":"collisium","s":191,"v":103,"c":"Алматы","t":"Общие","l":"https://t.me/collisium"},
{"name":"ҚМГ Инжиниринг/ҚМГИ","handle":"KMG_Engineering","s":188,"v":75,"c":"Казахстан","t":"Общие","l":"https://t.me/KMG_Engineering"},
{"name":"JadeRoadCars - Автомобили из Китая","handle":"jaderoadcars","s":185,"v":51,"c":"Казахстан","t":"Авто","l":"https://t.me/jaderoadcars"},
{"name":"Lobotomy lab","handle":"laminat_goofy","s":183,"v":115,"c":"Казахстан","t":"Общие","l":"https://t.me/laminat_goofy"},
{"name":"MarketStan","handle":"Market_Stan","s":183,"v":189,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/Market_Stan"},
{"name":"ГРАДОБЛОГ - Алматы 🇰🇿","handle":"gradoblog_ala","s":174,"v":104,"c":"Алматы","t":"Общие","l":"https://t.me/gradoblog_ala"},
{"name":"Millionaires club","handle":"SafeInvestAnalysis","s":170,"v":37,"c":"Казахстан","t":"Общие","l":"https://t.me/SafeInvestAnalysis"},
{"name":"Monte Verde не для всех","handle":"mb_krg","s":169,"v":57,"c":"Казахстан","t":"Общие","l":"https://t.me/mb_krg"},
{"name":"Kris_ cake","handle":"kriss_cake","s":166,"v":53,"c":"Казахстан","t":"Общие","l":"https://t.me/kriss_cake"},
{"name":"Максим, такое дело","handle":"makssgoo","s":157,"v":92,"c":"Казахстан","t":"Общие","l":"https://t.me/makssgoo"},
{"name":"супергеройская тусовка","handle":"superzlodeyslayatusovka","s":154,"v":59,"c":"Казахстан","t":"Общие","l":"https://t.me/superzlodeyslayatusovka"},
{"name":"REVERA Kazakhstan | юристы для бизнеса","handle":"REVERAKazakhstan","s":153,"v":107,"c":"Казахстан","t":"Бизнес","l":"https://t.me/REVERAKazakhstan"},
{"name":"АРТОН не Канон.","handle":"angelsStasa","s":150,"v":121,"c":"Казахстан","t":"Общие","l":"https://t.me/angelsStasa"},
{"name":"Tommy Muz 🇺🇲🎸","handle":"tommiyhilfigerr","s":148,"v":18,"c":"Казахстан","t":"Общие","l":"https://t.me/tommiyhilfigerr"},
{"name":"ВЕСЁЛЫЕ К🅰️РТИНКИ 🎨","handle":"smeh_kartinki","s":144,"v":39,"c":"Казахстан","t":"Общие","l":"https://t.me/smeh_kartinki"},
{"name":"Сколько дней ПСЖ без ЛЧ","handle":"whenPSGwinCL","s":137,"v":64,"c":"Казахстан","t":"Общие","l":"https://t.me/whenPSGwinCL"},
{"name":"ㅤıdłe* fąmıły","handle":"idlefamily1","s":130,"v":79,"c":"Казахстан","t":"Общие","l":"https://t.me/idlefamily1"},
{"name":"Камила может","handle":"kamilawhocan","s":129,"v":66,"c":"Казахстан","t":"Общие","l":"https://t.me/kamilawhocan"},
{"name":"Микрокредиты в Казахстане 2025, займы онлайн на карту","handle":"gdezaimkz","s":129,"v":28,"c":"Казахстан","t":"Общие","l":"https://t.me/gdezaimkz"},
{"name":"Burning heart","handle":"big_burning_heart","s":123,"v":88,"c":"Казахстан","t":"Общие","l":"https://t.me/big_burning_heart"},
{"name":"Подслушано у школы №73💦","handle":"podsl73","s":121,"v":58,"c":"Казахстан","t":"Общие","l":"https://t.me/podsl73"},
{"name":"– l'amour de vill ;","handle":"villslove","s":120,"v":51,"c":"Казахстан","t":"Общие","l":"https://t.me/villslove"},
{"name":"подвал сабо [рест]","handle":"f3mcelcore","s":120,"v":50,"c":"Казахстан","t":"Общие","l":"https://t.me/f3mcelcore"},
{"name":"Мосты - видео.","handle":"video_mostik","s":117,"v":239,"c":"Казахстан","t":"Общие","l":"https://t.me/video_mostik"},
{"name":"ICU.kz. Профессионально о коучинге в Казахстане","handle":"coachunion_kz","s":114,"v":72,"c":"Казахстан","t":"Общие","l":"https://t.me/coachunion_kz"},
{"name":"Раке, пиши... ✏️","handle":"rakepishi","s":114,"v":38,"c":"Казахстан","t":"Общие","l":"https://t.me/rakepishi"},
{"name":"Азат Машабаев / Электронная коммерция Казахстана","handle":"proecomkz7","s":111,"v":149,"c":"Казахстан","t":"Общие","l":"https://t.me/proecomkz7"},
{"name":"Биохакинг.Витамины. МЛМ Бизнес -EWA PRODUKT с Бабой Светой!","handle":"baba_sveta72_08","s":108,"v":22,"c":"Казахстан","t":"Бизнес","l":"https://t.me/baba_sveta72_08"},
{"name":"Клиенты из Телеграм I Андрей Смирнов","handle":"andrey002024","s":103,"v":22,"c":"Казахстан","t":"Общие","l":"https://t.me/andrey002024"},
{"name":"MYD Production","handle":"mydproduction","s":101,"v":41,"c":"Казахстан","t":"Общие","l":"https://t.me/mydproduction"},
{"name":"ASSALAWMA ALEYKUM","handle":"Qarekenshe_KokteyL","s":95,"v":3,"c":"Казахстан","t":"Общие","l":"https://t.me/Qarekenshe_KokteyL"},
{"name":"Щекоталочка","handle":"memerestroom","s":90,"v":23,"c":"Казахстан","t":"Общие","l":"https://t.me/memerestroom"},
{"name":"Haha imagine","handle":"hahaimagine","s":88,"v":54,"c":"Казахстан","t":"Общие","l":"https://t.me/hahaimagine"},
{"name":"With love, Ekaterina ❤️","handle":"I_am_Ekaterinaaa","s":88,"v":144,"c":"Казахстан","t":"Общие","l":"https://t.me/I_am_Ekaterinaaa"},
{"name":"ЦТО АБ Капитал AB Capital","handle":"cto_ab","s":84,"v":11,"c":"Казахстан","t":"Общие","l":"https://t.me/cto_ab"},
{"name":"ʍуᴩʍиᴄᴀᴀ","handle":"karw3y","s":81,"v":49,"c":"Казахстан","t":"Общие","l":"https://t.me/karw3y"},
{"name":"умрувянваре","handle":"m666wer","s":78,"v":91,"c":"Казахстан","t":"Общие","l":"https://t.me/m666wer"},
{"name":"‼️Сомнительные будни","handle":"signumortisss","s":78,"v":96,"c":"Казахстан","t":"Общие","l":"https://t.me/signumortisss"},
{"name":"webils_pro","handle":"webils_pro","s":78,"v":21,"c":"Казахстан","t":"Общие","l":"https://t.me/webils_pro"},
{"name":"Anime world ❤️‍🔥","handle":"anime_world_rai","s":74,"v":23,"c":"Казахстан","t":"Общие","l":"https://t.me/anime_world_rai"},
{"name":"Правильное питание и красота💖","handle":"praviloedy","s":73,"v":17,"c":"Казахстан","t":"Общие","l":"https://t.me/praviloedy"},
{"name":"По ту сторону клика | UX Research | Исследования","handle":"product_research_anna","s":72,"v":49,"c":"Казахстан","t":"Общие","l":"https://t.me/product_research_anna"},
{"name":"PR 💯% для пиарщиков и не только 🔥","handle":"abcolut","s":71,"v":12,"c":"Казахстан","t":"Общие","l":"https://t.me/abcolut"},
{"name":"qañtardagy tuimedaq","handle":"qitimirayaz","s":69,"v":46,"c":"Казахстан","t":"Общие","l":"https://t.me/qitimirayaz"},
{"name":"Lukas Crysteffor⚔️🔥","handle":"Lukaseffor","s":66,"v":21,"c":"Казахстан","t":"Общие","l":"https://t.me/Lukaseffor"},
{"name":"MV.Digital | Всё о маркетинге и digital","handle":"mvdigitalkz","s":62,"v":30,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/mvdigitalkz"},
{"name":"Гуманист ° HumanEst","handle":"veratyanblog","s":62,"v":9,"c":"Казахстан","t":"Общие","l":"https://t.me/veratyanblog"},
{"name":"🇰🇿 INNOVATION.KZ / SMART TECHNOLOGY","handle":"innovationkaz","s":58,"v":8,"c":"Казахстан","t":"Общие","l":"https://t.me/innovationkaz"},
{"name":"tsusyndrome SOOBIN 🎎","handle":"s4kanata","s":54,"v":22,"c":"Казахстан","t":"Общие","l":"https://t.me/s4kanata"},
{"name":"Промокоды и скидки России и Казахстана","handle":"promo_ru_kaz","s":52,"v":2,"c":"Казахстан","t":"Общие","l":"https://t.me/promo_ru_kaz"},
{"name":"Кот дня","handle":"catdayever","s":50,"v":19,"c":"Казахстан","t":"Общие","l":"https://t.me/catdayever"},
{"name":"꧁AfterDesign꧂","handle":"AftergrouddChannel","s":50,"v":7,"c":"Казахстан","t":"Общие","l":"https://t.me/AftergrouddChannel"},
{"name":"Все в моем доме👍","handle":"vseVdome","s":48,"v":3,"c":"Казахстан","t":"Общие","l":"https://t.me/vseVdome"},
{"name":"Татьяна Мурзина | Стратегия влияния","handle":"tmmarkstrat","s":48,"v":18,"c":"Казахстан","t":"Общие","l":"https://t.me/tmmarkstrat"},
{"name":"Жизнь ТОЧИЛКИ2008","handle":"tochilkiinn","s":47,"v":75,"c":"Казахстан","t":"Общие","l":"https://t.me/tochilkiinn"},
{"name":"Сайяны Усера","handle":"gayqwerty","s":43,"v":13,"c":"Казахстан","t":"Общие","l":"https://t.me/gayqwerty"},
{"name":"| Авы, тачки, автомобили, эдиты |","handle":"carsoav","s":43,"v":10,"c":"Казахстан","t":"Авто","l":"https://t.me/carsoav"},
{"name":"Қазақ братаны","handle":"brianmoserlove","s":42,"v":2,"c":"Казахстан","t":"Общие","l":"https://t.me/brianmoserlove"},
{"name":"Вкусные кулинарные | Рецепты","handle":"Degusto_Ok","s":39,"v":9,"c":"Казахстан","t":"Еда/Досуг","l":"https://t.me/Degusto_Ok"},
{"name":"Анжелика Матвеева | BIM & Engineering","handle":"matveyevalife","s":39,"v":215,"c":"Казахстан","t":"Общие","l":"https://t.me/matveyevalife"},
{"name":"Mutalov Venture Club","handle":"mutalov_venture_club","s":33,"v":60,"c":"Казахстан","t":"Общие","l":"https://t.me/mutalov_venture_club"},
{"name":"Мемасоидная гусеница Гриша","handle":"gusenitsagrisha","s":30,"v":10,"c":"Казахстан","t":"Общие","l":"https://t.me/gusenitsagrisha"},
{"name":"Поля векторных смещений 👁️","handle":"ffish_ka","s":29,"v":41,"c":"Казахстан","t":"Общие","l":"https://t.me/ffish_ka"},
{"name":"Дедовская жизнь","handle":"Eblan1kl","s":28,"v":28,"c":"Казахстан","t":"Общие","l":"https://t.me/Eblan1kl"},
{"name":"CoSMMo - интернет агентство","handle":"cosmmokz","s":28,"v":8,"c":"Казахстан","t":"Общие","l":"https://t.me/cosmmokz"},
{"name":"Приколы Динуса","handle":"prikoly_dinusa","s":27,"v":9,"c":"Казахстан","t":"Общие","l":"https://t.me/prikoly_dinusa"},
{"name":"комната крыски","handle":"myshkamypka","s":27,"v":26,"c":"Казахстан","t":"Общие","l":"https://t.me/myshkamypka"},
{"name":"Школа Аниматроникав","handle":"shakal3dmlgpro","s":26,"v":12,"c":"Казахстан","t":"Общие","l":"https://t.me/shakal3dmlgpro"},
{"name":"𝓯𝓻𝓮𝓪𝓴𝔂 corvus","handle":"sexpal69","s":26,"v":55,"c":"Казахстан","t":"Общие","l":"https://t.me/sexpal69"},
{"name":"RentalWagons","handle":"rental_wagons","s":26,"v":18,"c":"Казахстан","t":"Общие","l":"https://t.me/rental_wagons"},
{"name":"я ем арсения, а ты? كل النور لله","handle":"sealinme","s":24,"v":14,"c":"Казахстан","t":"Общие","l":"https://t.me/sealinme"},
{"name":"Бирюзовая кухня","handle":"vegweek108","s":24,"v":28,"c":"Казахстан","t":"Общие","l":"https://t.me/vegweek108"},
{"name":"Инвестор из села💲","handle":"investorizsela","s":24,"v":1,"c":"Казахстан","t":"Общие","l":"https://t.me/investorizsela"},
{"name":"Отборное ололо","handle":"otbornoe_ololo","s":23,"v":11,"c":"Казахстан","t":"Общие","l":"https://t.me/otbornoe_ololo"},
{"name":"ench.sori","handle":"enchriz","s":21,"v":16,"c":"Казахстан","t":"Общие","l":"https://t.me/enchriz"},
{"name":"Тъут ксо","handle":"kso42","s":21,"v":18,"c":"Казахстан","t":"Общие","l":"https://t.me/kso42"},
{"name":"яйца клуб","handle":"thoughtsofds","s":21,"v":30,"c":"Казахстан","t":"Общие","l":"https://t.me/thoughtsofds"},
{"name":"прокрастинация🕳️👨‍🦽","handle":"bolshayajirnayajopa","s":16,"v":23,"c":"Казахстан","t":"Общие","l":"https://t.me/bolshayajirnayajopa"},
{"name":"adikalone","handle":"dlmrb","s":15,"v":25,"c":"Казахстан","t":"Общие","l":"https://t.me/dlmrb"},
{"name":"paradise","handle":"blessndkeep","s":14,"v":15,"c":"Казахстан","t":"Общие","l":"https://t.me/blessndkeep"},
{"name":"🧭C(O38️⃣","handle":"inSOYUZ","s":14,"v":50,"c":"Казахстан","t":"Общие","l":"https://t.me/inSOYUZ"},
{"name":"gameboy в Италии","handle":"yusufiik","s":11,"v":22,"c":"Казахстан","t":"Общие","l":"https://t.me/yusufiik"},
{"name":"Abai shitpost","handle":"abaichannel13","s":10,"v":17,"c":"Казахстан","t":"Общие","l":"https://t.me/abaichannel13"},
{"name":"｡～Канал Пиджи; Непростая жизяка мелкого!!!～｡⁠","handle":"PJslife","s":10,"v":9,"c":"Казахстан","t":"Общие","l":"https://t.me/PJslife"},
{"name":"VanLive🙃😎🤜","handle":"VanMagVigor","s":7,"v":14,"c":"Казахстан","t":"Общие","l":"https://t.me/VanMagVigor"},
{"name":"Госзакупки Казахстан","handle":"kzgoszakup","s":7,"v":2,"c":"Казахстан","t":"Общие","l":"https://t.me/kzgoszakup"},
{"name":"KWAS KYBAS","handle":"Kvaskybas666","s":5,"v":5,"c":"Казахстан","t":"Общие","l":"https://t.me/Kvaskybas666"},
{"name":"Cheat Code - обучение контекстной рекламе","handle":"cheat_code_ads","s":5,"v":1,"c":"Казахстан","t":"Маркетинг","l":"https://t.me/cheat_code_ads"},
{"name":"Eurasia Infrastructure Fund","handle":"EurasiaInfrastructureFunds","s":4,"v":5,"c":"Казахстан","t":"Общие","l":"https://t.me/EurasiaInfrastructureFunds"},
{"name":"Проектная компания \"EngPro\"","handle":"techobsl","s":3,"v":1,"c":"Казахстан","t":"Общие","l":"https://t.me/techobsl"},
{"name":"Trader Bot","handle":"traderbotV2","s":2,"v":2,"c":"Казахстан","t":"Общие","l":"https://t.me/traderbotV2"}
];
const TELEGRAM_CITIES=["Актау", "Актобе", "Алматы", "Астана", "Атырау", "Казахстан", "Караганда", "Павлодар", "Семей", "Тараз", "Уральск", "Шымкент"];
const TELEGRAM_CATS=["Авто", "Бизнес", "Еда/Досуг", "Маркетинг", "Недвижимость", "Новостные", "Образование", "Общие", "Развлечения", "Спорт"];
