const TIKTOK_DB=[
  {"name":"Aliev Omar (Omari)","handle":"omari.to","s":54500000,"v":5000000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@omari.to"},
  {"name":"HOMA","handle":"homm9k","s":54100000,"v":4000000,"c":"Казахстан","t":"Юмор","l":"https://tiktok.com/@homm9k"},
  {"name":"Дина Саева","handle":"dinasaeva","s":19000000,"v":3000000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@dinasaeva"},
  {"name":"Димаш Кудайберген","handle":"dimaborisevich","s":10500000,"v":2000000,"c":"Актобе","t":"Музыка","l":"https://tiktok.com/@dimaborisevich"},
  {"name":"Нуртас Адамбай","handle":"nurtasadambay","s":8500000,"v":1500000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@nurtasadambay"},
  {"name":"Мади Бекдаир","handle":"madibekdair","s":7000000,"v":1200000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@madibekdair"},
  {"name":"Darkhan Juzz","handle":"darkhanjuzz","s":6800000,"v":1000000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@darkhanjuzz"},
  {"name":"Abzal Rassul","handle":"abzal_rassul","s":6500000,"v":900000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@abzal_rassul"},
  {"name":"Aisha Aset","handle":"aisha_aset","s":6200000,"v":800000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@aisha_aset"},
  {"name":"Jeltoksan","handle":"jeltoksan_","s":5800000,"v":900000,"c":"Нур-Султан","t":"Юмор","l":"https://tiktok.com/@jeltoksan_"},
  {"name":"Dana Bazilova","handle":"danabazilova","s":5500000,"v":700000,"c":"Алматы","t":"Танцы","l":"https://tiktok.com/@danabazilova"},
  {"name":"Sakura","handle":"sakura.kz","s":5200000,"v":800000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@sakura.kz"},
  {"name":"Arman Kenzhebayev","handle":"armankenzhebayev","s":5000000,"v":700000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@armankenzhebayev"},
  {"name":"Erbol Khamitov","handle":"erbolkhamitov","s":4800000,"v":600000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@erbolkhamitov"},
  {"name":"Makpal Issabayeva","handle":"makpal_issabayeva","s":4500000,"v":500000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@makpal_issabayeva"},
  {"name":"Aizhan Bayanova","handle":"aizhan_bayanova","s":4300000,"v":600000,"c":"Алматы","t":"Танцы","l":"https://tiktok.com/@aizhan_bayanova"},
  {"name":"Nurlybek","handle":"nurlybek.kz","s":4200000,"v":500000,"c":"Шымкент","t":"Юмор","l":"https://tiktok.com/@nurlybek.kz"},
  {"name":"Aisultan Seitov","handle":"aisultan_seitov","s":4100000,"v":400000,"c":"Алматы","t":"Лайфстайл","l":"https://tiktok.com/@aisultan_seitov"},
  {"name":"Baller","handle":"baller.kz","s":4000000,"v":500000,"c":"Алматы","t":"Спорт","l":"https://tiktok.com/@baller.kz"},
  {"name":"Kamilla Kozhakhmetova","handle":"kamilla_koz","s":3800000,"v":400000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@kamilla_koz"},
  {"name":"Damir Baigarashev","handle":"damir_baigarashev","s":3700000,"v":400000,"c":"Караганда","t":"Юмор","l":"https://tiktok.com/@damir_baigarashev"},
  {"name":"Madina Batyrkhan","handle":"madina_batyrkhan","s":3600000,"v":350000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@madina_batyrkhan"},
  {"name":"Sultan Skateboard","handle":"sultan_skate","s":3500000,"v":400000,"c":"Алматы","t":"Спорт","l":"https://tiktok.com/@sultan_skate"},
  {"name":"Рустем","handle":"rustem_yt","s":3400000,"v":300000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@rustem_yt"},
  {"name":"Aiym","handle":"aiym.kz","s":3300000,"v":350000,"c":"Нур-Султан","t":"Танцы","l":"https://tiktok.com/@aiym.kz"},
  {"name":"Malika Orazbayeva","handle":"malika_oraz","s":3200000,"v":300000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@malika_oraz"},
  {"name":"Tamerlan Tazhibayev","handle":"tamerlan_taz","s":3100000,"v":250000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@tamerlan_taz"},
  {"name":"Zhan Akhmetov","handle":"zhan_akhmetov","s":3000000,"v":300000,"c":"Алматы","t":"Музыка","l":"https://tiktok.com/@zhan_akhmetov"},
  {"name":"Madiyar","handle":"madiyar.kz","s":2900000,"v":250000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@madiyar.kz"},
  {"name":"Asel Kozhakhmet","handle":"asel_kozhakhmet","s":2800000,"v":250000,"c":"Нур-Султан","t":"Лайфстайл","l":"https://tiktok.com/@asel_kozhakhmet"},
  {"name":"Nurlan Saburov","handle":"nurlansaburov","s":2700000,"v":500000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@nurlansaburov"},
  {"name":"Toregali Toreali","handle":"toregali_toreali","s":2600000,"v":300000,"c":"Алматы","t":"Музыка","l":"https://tiktok.com/@toregali_toreali"},
  {"name":"Kazakh Beauty","handle":"kazakh_beauty","s":2500000,"v":200000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@kazakh_beauty"},
  {"name":"Bekzat Baimukhanbetov","handle":"bekzat_bm","s":2400000,"v":200000,"c":"Шымкент","t":"Юмор","l":"https://tiktok.com/@bekzat_bm"},
  {"name":"Dias Kalenov","handle":"dias_kalenov","s":2350000,"v":200000,"c":"Алматы","t":"Общие","l":"https://tiktok.com/@dias_kalenov"},
  {"name":"Aknur Sadvakassova","handle":"aknur_sad","s":2300000,"v":180000,"c":"Алматы","t":"Танцы","l":"https://tiktok.com/@aknur_sad"},
  {"name":"Yernar Kuat","handle":"yernarkuat","s":2250000,"v":200000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@yernarkuat"},
  {"name":"Dina Tokpanova","handle":"dina_tokpanova","s":2200000,"v":180000,"c":"Нур-Султан","t":"Лайфстайл","l":"https://tiktok.com/@dina_tokpanova"},
  {"name":"Arailym","handle":"arailym.tt","s":2100000,"v":170000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@arailym.tt"},
  {"name":"Sanzhar Madiyev","handle":"sanzhar_madiyev","s":2050000,"v":300000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@sanzhar_madiyev"},
  {"name":"Bagdat Musin","handle":"bagdat_musin","s":2000000,"v":150000,"c":"Нур-Султан","t":"Бизнес","l":"https://tiktok.com/@bagdat_musin"},
  {"name":"Assylzhan","handle":"assylzhan.tt","s":1950000,"v":150000,"c":"Алматы","t":"Общие","l":"https://tiktok.com/@assylzhan.tt"},
  {"name":"Miras Zhugunusov","handle":"miras_zhug","s":1900000,"v":150000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@miras_zhug"},
  {"name":"Ainur Tursynbay","handle":"ainur_tursynbay","s":1850000,"v":140000,"c":"Шымкент","t":"Красота","l":"https://tiktok.com/@ainur_tursynbay"},
  {"name":"QazaqFood","handle":"qazaq.food","s":1800000,"v":200000,"c":"Алматы","t":"Еда","l":"https://tiktok.com/@qazaq.food"},
  {"name":"Beibit Alibekov","handle":"beibit_alibekov","s":1750000,"v":200000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@beibit_alibekov"},
  {"name":"Azamat Musagaliyev","handle":"azamat_musagaliyev","s":1700000,"v":150000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@azamat_musagaliyev"},
  {"name":"Gulnaz Kz","handle":"gulnaz.kz","s":1650000,"v":120000,"c":"Нур-Султан","t":"Лайфстайл","l":"https://tiktok.com/@gulnaz.kz"},
  {"name":"Daniar Yessimov","handle":"daniar_yess","s":1600000,"v":130000,"c":"Алматы","t":"Общие","l":"https://tiktok.com/@daniar_yess"},
  {"name":"Zhuldyz Sharip","handle":"zhuldyz_sharip","s":1550000,"v":120000,"c":"Алматы","t":"Музыка","l":"https://tiktok.com/@zhuldyz_sharip"},
  {"name":"KZ Basketball","handle":"kz_basketball","s":1500000,"v":100000,"c":"Алматы","t":"Спорт","l":"https://tiktok.com/@kz_basketball"},
  {"name":"Ermek Tursynbayev","handle":"ermek_tursynbayev","s":1450000,"v":100000,"c":"Караганда","t":"Юмор","l":"https://tiktok.com/@ermek_tursynbayev"},
  {"name":"Almira Tursyn","handle":"almira_tursyn","s":1400000,"v":120000,"c":"Алматы","t":"Танцы","l":"https://tiktok.com/@almira_tursyn"},
  {"name":"Ернар Айдар","handle":"ernar_aidar","s":1380000,"v":150000,"c":"Алматы","t":"Музыка","l":"https://tiktok.com/@ernar_aidar"},
  {"name":"Sultan Nurkenov","handle":"sultan_nurkenov","s":1350000,"v":100000,"c":"Алматы","t":"Лайфстайл","l":"https://tiktok.com/@sultan_nurkenov"},
  {"name":"Alima Beauty","handle":"alima_beauty","s":1300000,"v":100000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@alima_beauty"},
  {"name":"Ayan Kurmangali","handle":"ayan_kurman","s":1250000,"v":100000,"c":"Нур-Султан","t":"Образование","l":"https://tiktok.com/@ayan_kurman"},
  {"name":"Kairat Nurtas","handle":"kairat_nurtas","s":1200000,"v":200000,"c":"Алматы","t":"Музыка","l":"https://tiktok.com/@kairat_nurtas"},
  {"name":"Kazakh Chef","handle":"kazakh_chef","s":1150000,"v":100000,"c":"Алматы","t":"Еда","l":"https://tiktok.com/@kazakh_chef"},
  {"name":"Bolat Serikbayev","handle":"bolat_serik","s":1100000,"v":80000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@bolat_serik"},
  {"name":"Saltanat Mukatova","handle":"saltanat_muk","s":1050000,"v":80000,"c":"Шымкент","t":"Красота","l":"https://tiktok.com/@saltanat_muk"},
  {"name":"Askar Martial","handle":"askar_martial","s":1000000,"v":100000,"c":"Алматы","t":"Спорт","l":"https://tiktok.com/@askar_martial"},
  {"name":"Zarina Dance","handle":"zarina_dance","s":980000,"v":80000,"c":"Алматы","t":"Танцы","l":"https://tiktok.com/@zarina_dance"},
  {"name":"KZ Fitness","handle":"kz_fitness","s":950000,"v":70000,"c":"Алматы","t":"Спорт","l":"https://tiktok.com/@kz_fitness"},
  {"name":"Alua Abisheva","handle":"alua_abisheva","s":920000,"v":70000,"c":"Нур-Султан","t":"Лайфстайл","l":"https://tiktok.com/@alua_abisheva"},
  {"name":"Мейрхан Каратаев","handle":"meyrkhan_k","s":900000,"v":80000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@meyrkhan_k"},
  {"name":"Dana Cook KZ","handle":"dana_cook_kz","s":880000,"v":70000,"c":"Алматы","t":"Еда","l":"https://tiktok.com/@dana_cook_kz"},
  {"name":"Nariman Nauryz","handle":"nariman_nauryz","s":850000,"v":60000,"c":"Караганда","t":"Юмор","l":"https://tiktok.com/@nariman_nauryz"},
  {"name":"BiznesKZ","handle":"biznes.kz","s":830000,"v":50000,"c":"Алматы","t":"Бизнес","l":"https://tiktok.com/@biznes.kz"},
  {"name":"Adina Teach","handle":"adina_teach","s":800000,"v":60000,"c":"Нур-Султан","t":"Образование","l":"https://tiktok.com/@adina_teach"},
  {"name":"Symbat KZ","handle":"symbat_kz","s":780000,"v":50000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@symbat_kz"},
  {"name":"Yerkin Gamez","handle":"yerkin_gamez","s":750000,"v":60000,"c":"Алматы","t":"Общие","l":"https://tiktok.com/@yerkin_gamez"},
  {"name":"Maksat Sport","handle":"maksat_sport","s":720000,"v":50000,"c":"Алматы","t":"Спорт","l":"https://tiktok.com/@maksat_sport"},
  {"name":"Moldir Fashion","handle":"moldir_fashion","s":700000,"v":50000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@moldir_fashion"},
  {"name":"Talgat Comedian","handle":"talgat_comedy","s":680000,"v":50000,"c":"Шымкент","t":"Юмор","l":"https://tiktok.com/@talgat_comedy"},
  {"name":"Saulet Education","handle":"saulet_edu","s":650000,"v":40000,"c":"Нур-Султан","t":"Образование","l":"https://tiktok.com/@saulet_edu"},
  {"name":"Baurzhan Music","handle":"baurzhan_music","s":630000,"v":50000,"c":"Алматы","t":"Музыка","l":"https://tiktok.com/@baurzhan_music"},
  {"name":"Astana Life","handle":"astana_life","s":600000,"v":40000,"c":"Нур-Султан","t":"Лайфстайл","l":"https://tiktok.com/@astana_life"},
  {"name":"Aida Food KZ","handle":"aida_food_kz","s":580000,"v":40000,"c":"Алматы","t":"Еда","l":"https://tiktok.com/@aida_food_kz"},
  {"name":"Erlan Business","handle":"erlan_biz","s":550000,"v":30000,"c":"Алматы","t":"Бизнес","l":"https://tiktok.com/@erlan_biz"},
  {"name":"Samal Dance","handle":"samal_dance","s":530000,"v":40000,"c":"Алматы","t":"Танцы","l":"https://tiktok.com/@samal_dance"},
  {"name":"Almaty Foodie","handle":"almaty_foodie","s":500000,"v":40000,"c":"Алматы","t":"Еда","l":"https://tiktok.com/@almaty_foodie"},
  {"name":"Kanat Tech","handle":"kanat_tech","s":480000,"v":30000,"c":"Алматы","t":"Образование","l":"https://tiktok.com/@kanat_tech"},
  {"name":"Zhanna Laugh","handle":"zhanna_laugh","s":450000,"v":30000,"c":"Караганда","t":"Юмор","l":"https://tiktok.com/@zhanna_laugh"},
  {"name":"Almas Lifestyle","handle":"almas_lifestyle","s":430000,"v":25000,"c":"Алматы","t":"Лайфстайл","l":"https://tiktok.com/@almas_lifestyle"},
  {"name":"Askhat Football","handle":"askhat_football","s":400000,"v":30000,"c":"Алматы","t":"Спорт","l":"https://tiktok.com/@askhat_football"},
  {"name":"Marjan Beauty","handle":"marjan_beauty","s":380000,"v":25000,"c":"Шымкент","t":"Красота","l":"https://tiktok.com/@marjan_beauty"},
  {"name":"Qazaq Music","handle":"qazaq_music","s":350000,"v":30000,"c":"Алматы","t":"Музыка","l":"https://tiktok.com/@qazaq_music"},
  {"name":"Serik Entrepreneur","handle":"serik_biz","s":330000,"v":20000,"c":"Нур-Султан","t":"Бизнес","l":"https://tiktok.com/@serik_biz"},
  {"name":"Almaty Vlogger","handle":"almaty_vlogger","s":310000,"v":20000,"c":"Алматы","t":"Лайфстайл","l":"https://tiktok.com/@almaty_vlogger"},
  {"name":"Gulim Cook","handle":"gulim_cook","s":300000,"v":25000,"c":"Алматы","t":"Еда","l":"https://tiktok.com/@gulim_cook"},
  {"name":"Batyrkhan Singer","handle":"batyrkhan_singer","s":280000,"v":20000,"c":"Алматы","t":"Музыка","l":"https://tiktok.com/@batyrkhan_singer"},
  {"name":"Aktobe Life","handle":"aktobe_life","s":260000,"v":15000,"c":"Актобе","t":"Лайфстайл","l":"https://tiktok.com/@aktobe_life"},
  {"name":"Saya Edu","handle":"saya_edu","s":250000,"v":15000,"c":"Нур-Султан","t":"Образование","l":"https://tiktok.com/@saya_edu"},
  {"name":"Kassym Smile","handle":"kassym_smile","s":230000,"v":15000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@kassym_smile"},
  {"name":"Shymkent Food","handle":"shymkent_food","s":220000,"v":15000,"c":"Шымкент","t":"Еда","l":"https://tiktok.com/@shymkent_food"},
  {"name":"Nurbol Sport","handle":"nurbol_sport","s":200000,"v":10000,"c":"Алматы","t":"Спорт","l":"https://tiktok.com/@nurbol_sport"},
  {"name":"KZ Dance Crew","handle":"kz_dance_crew","s":190000,"v":15000,"c":"Алматы","t":"Танцы","l":"https://tiktok.com/@kz_dance_crew"},
  {"name":"Zhenis Business","handle":"zhenis_biz","s":180000,"v":10000,"c":"Нур-Султан","t":"Бизнес","l":"https://tiktok.com/@zhenis_biz"},
  {"name":"Meruert Style","handle":"meruert_style","s":170000,"v":10000,"c":"Алматы","t":"Красота","l":"https://tiktok.com/@meruert_style"},
  {"name":"Dimash Clips","handle":"dimash_clips","s":160000,"v":20000,"c":"Казахстан","t":"Музыка","l":"https://tiktok.com/@dimash_clips"},
  {"name":"KZ Humor","handle":"kz_humor","s":150000,"v":10000,"c":"Алматы","t":"Юмор","l":"https://tiktok.com/@kz_humor"}
];
const TIKTOK_CITIES=["Алматы","Нур-Султан","Шымкент","Караганда","Актобе","Казахстан"];
const TIKTOK_CATS=["Юмор","Танцы","Музыка","Лайфстайл","Красота","Образование","Еда","Спорт","Бизнес","Общие"];
