const YOUTUBE_DB=[
  {"name":"Elsa Arca","handle":"ElsaArca","s":16100000,"v":4800000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@ElsaArca"},
  {"name":"Симбочка Пимпочка","handle":"SimbochkaPimpochka","s":14500000,"v":8100000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@SimbochkaPimpochka"},
  {"name":"YOLO HOUSE","handle":"YOLOHOUSE","s":7380000,"v":1270000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@YOLOHOUSE"},
  {"name":"bip_house","handle":"bip_house","s":6970000,"v":1390000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@bip_house"},
  {"name":"Финиль Shorts","handle":"FinilShorts","s":6660000,"v":2990000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@FinilShorts"},
  {"name":"Аминка Витаминка","handle":"AminkaVitaminka","s":6360000,"v":3830000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@AminkaVitaminka"},
  {"name":"Domino Girl","handle":"DominoGirl","s":5810000,"v":917000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@DominoGirl"},
  {"name":"SQUAD BRO SHOW","handle":"SQUADBROSHOW","s":4960000,"v":2925000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@SQUADBROSHOW"},
  {"name":"Khabar TV","handle":"KhabarTV","s":4130000,"v":78000,"c":"Астана","t":"Новости","l":"https://youtube.com/@KhabarTV"},
  {"name":"homm9k","handle":"homm9k","s":4060000,"v":1122000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@homm9k"},
  {"name":"Юный Повар","handle":"YunyyPovar","s":4040000,"v":3680000,"c":"Казахстан","t":"Еда","l":"https://youtube.com/@YunyyPovar"},
  {"name":"Светлый Voice","handle":"SvetlyyVoice","s":3980000,"v":2920000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@SvetlyyVoice"},
  {"name":"⋆ Kiara BunY","handle":"KiaraBunY","s":3940000,"v":6050000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@KiaraBunY"},
  {"name":"Zaka Habarit","handle":"ZakaHabarit","s":3830000,"v":1858000,"c":"Казахстан","t":"Музыка","l":"https://youtube.com/@ZakaHabarit"},
  {"name":"Седьмой канал","handle":"7kanalKZ","s":3770000,"v":152000,"c":"Алматы","t":"Развлечения","l":"https://youtube.com/@7kanalKZ"},
  {"name":"Qazaqstan TV","handle":"QazaqstanTV","s":3620000,"v":19000,"c":"Астана","t":"Новости","l":"https://youtube.com/@QazaqstanTV"},
  {"name":"MnogoNotka.Com","handle":"MnogoNotkaCom","s":3470000,"v":481000,"c":"Казахстан","t":"Музыка","l":"https://youtube.com/@MnogoNotkaCom"},
  {"name":"ТОЙ ДУМАН","handle":"ToyDuman","s":3440000,"v":912000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@ToyDuman"},
  {"name":"GAKKU TV","handle":"GakkuTV","s":3370000,"v":822000,"c":"Алматы","t":"Развлечения","l":"https://youtube.com/@GakkuTV"},
  {"name":"Farakicks","handle":"Farakicks","s":3160000,"v":1507000,"c":"Казахстан","t":"Спорт","l":"https://youtube.com/@Farakicks"},
  {"name":"Бабка Шоу","handle":"BabkaShow","s":3140000,"v":245000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@BabkaShow"},
  {"name":"Финиль из Огайо","handle":"FinilOhio","s":3110000,"v":1364000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@FinilOhio"},
  {"name":"Еда на любой вкус","handle":"EdaNaLuboyVkus","s":3070000,"v":381000,"c":"Казахстан","t":"Еда","l":"https://youtube.com/@EdaNaLuboyVkus"},
  {"name":"natka_promag","handle":"natka_promag","s":3040000,"v":307000,"c":"Казахстан","t":"Юмор","l":"https://youtube.com/@natka_promag"},
  {"name":"Dimash Qudaibergen","handle":"DimashQudaibergen","s":3020000,"v":2553000,"c":"Астана","t":"Музыка","l":"https://youtube.com/@DimashQudaibergen"},
  {"name":"WINARES EDITS","handle":"WINARESEDITS","s":2960000,"v":22810000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@WINARESEDITS"},
  {"name":"AJIuKZ","handle":"AJIuKZ","s":2920000,"v":687000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@AJIuKZ"},
  {"name":"СПС","handle":"saspens","s":2740000,"v":1075000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@saspens"},
  {"name":"NurChannel","handle":"NurChannel","s":2690000,"v":724000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@NurChannel"},
  {"name":"Balapan TV","handle":"BalapanTV","s":2510000,"v":94000,"c":"Астана","t":"Развлечения","l":"https://youtube.com/@BalapanTV"},
  {"name":"Marat Oralgazin","handle":"MaratOralgazin","s":2460000,"v":508000,"c":"Алматы","t":"Юмор","l":"https://youtube.com/@MaratOralgazin"},
  {"name":"Erkinrx","handle":"Erkinrx","s":2460000,"v":562000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@Erkinrx"},
  {"name":"Рамина Алмас","handle":"RaminaAlmas","s":2430000,"v":3023000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@RaminaAlmas"},
  {"name":"Meyram Cinema","handle":"MeyramCinema","s":2420000,"v":431000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@MeyramCinema"},
  {"name":"KTK TV","handle":"KTKTV","s":2410000,"v":91000,"c":"Алматы","t":"Новости","l":"https://youtube.com/@KTKTV"},
  {"name":"Настя Манастя","handle":"NastyaManastya","s":2390000,"v":1587000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@NastyaManastya"},
  {"name":"Азамат Мусагалиев","handle":"AzamatMusagaliev","s":2330000,"v":1172000,"c":"Алматы","t":"Юмор","l":"https://youtube.com/@AzamatMusagaliev"},
  {"name":"Asel Mustafa","handle":"AselMustafa","s":2270000,"v":8230000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@AselMustafa"},
  {"name":"QosLike / ҚосЛайк","handle":"QosLike","s":2250000,"v":346000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@QosLike"},
  {"name":"Лолотрек - Майнкрафт","handle":"Lolotrek","s":2240000,"v":1194000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@Lolotrek"},
  {"name":"Первый канал Евразия","handle":"1TVEurasia","s":2240000,"v":24000,"c":"Алматы","t":"Новости","l":"https://youtube.com/@1TVEurasia"},
  {"name":"Adaliatta","handle":"Adaliatta","s":2230000,"v":903000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@Adaliatta"},
  {"name":"Сезім Бағы","handle":"SezimBagy","s":2180000,"v":157000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@SezimBagy"},
  {"name":"Телеканал 24kz","handle":"24kz","s":2170000,"v":3000,"c":"Астана","t":"Новости","l":"https://youtube.com/@24kz"},
  {"name":"Владос-AUTO","handle":"VladosAUTO","s":2150000,"v":1328000,"c":"Казахстан","t":"Авто","l":"https://youtube.com/@VladosAUTO"},
  {"name":"Информбюро 31","handle":"31kanal","s":2120000,"v":16000,"c":"Алматы","t":"Новости","l":"https://youtube.com/@31kanal"},
  {"name":"azabra3a","handle":"azabra3a","s":2030000,"v":737000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@azabra3a"},
  {"name":"Софья Земляная","handle":"SofyaZemlyanaya","s":2020000,"v":517000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@SofyaZemlyanaya"},
  {"name":"Azattyq TV","handle":"AzattyqTV","s":1910000,"v":44000,"c":"Алматы","t":"Новости","l":"https://youtube.com/@AzattyqTV"},
  {"name":"Simple Idea","handle":"SimpleIdea","s":1910000,"v":17123000,"c":"Казахстан","t":"Технологии","l":"https://youtube.com/@SimpleIdea"},
  {"name":"Mittivine","handle":"Mittivine","s":1800000,"v":1306000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@Mittivine"},
  {"name":"Телеканал Астана","handle":"AstanaTV","s":1790000,"v":9000,"c":"Астана","t":"Новости","l":"https://youtube.com/@AstanaTV"},
  {"name":"Даник Кек","handle":"DanikKek","s":1780000,"v":589000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@DanikKek"},
  {"name":"TheLoop","handle":"TheLoop","s":1680000,"v":2076000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@TheLoop"},
  {"name":"OCTAGON TV","handle":"OCTAGONTV","s":1590000,"v":516000,"c":"Казахстан","t":"Спорт","l":"https://youtube.com/@OCTAGONTV"},
  {"name":"NTK TV","handle":"NTKTV","s":1580000,"v":327000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@NTKTV"},
  {"name":"Kairat Nurtas","handle":"KairatNurtas","s":1460000,"v":3369000,"c":"Алматы","t":"Музыка","l":"https://youtube.com/@KairatNurtas"},
  {"name":"Клиника доктора Шурова","handle":"DrShurov","s":1460000,"v":332000,"c":"Казахстан","t":"Образование","l":"https://youtube.com/@DrShurov"},
  {"name":"Dalbek","handle":"Dalbek","s":1420000,"v":1568000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@Dalbek"},
  {"name":"dar1n_tt","handle":"dar1n_tt","s":1420000,"v":521000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@dar1n_tt"},
  {"name":"RFC Fighting Championship","handle":"RFC","s":1410000,"v":1054000,"c":"Казахстан","t":"Спорт","l":"https://youtube.com/@RFC"},
  {"name":"JOKIT SHORTS","handle":"JOKITSHORTS","s":1370000,"v":524000,"c":"Казахстан","t":"Юмор","l":"https://youtube.com/@JOKITSHORTS"},
  {"name":"Остап Парфёнов","handle":"OstapParfenov","s":1340000,"v":399000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@OstapParfenov"},
  {"name":"Ekaterina Saibel","handle":"EkaterinaSaibel","s":1340000,"v":277000,"c":"Казахстан","t":"Красота","l":"https://youtube.com/@EkaterinaSaibel"},
  {"name":"TENGRI TV","handle":"TengriTV","s":1280000,"v":72000,"c":"Астана","t":"Новости","l":"https://youtube.com/@TengriTV"},
  {"name":"anasrassia","handle":"anasrassia","s":1240000,"v":1067000,"c":"Казахстан","t":"Музыка","l":"https://youtube.com/@anasrassia"},
  {"name":"Bjornzz","handle":"Bjornzz","s":1190000,"v":3770000,"c":"Казахстан","t":"Музыка","l":"https://youtube.com/@Bjornzz"},
  {"name":"DerbyEdits","handle":"DerbyEdits","s":1180000,"v":1603000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@DerbyEdits"},
  {"name":"AIRAN","handle":"AIRAN","s":1130000,"v":73000,"c":"Казахстан","t":"Новости","l":"https://youtube.com/@AIRAN"},
  {"name":"Amirchik","handle":"Amirchik","s":1120000,"v":637000,"c":"Казахстан","t":"Музыка","l":"https://youtube.com/@Amirchik"},
  {"name":"Mirazimov Family","handle":"MirazimovFamily","s":1100000,"v":1489000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@MirazimovFamily"},
  {"name":"JUSTKING REAL","handle":"JUSTKINGREAL","s":1070000,"v":1837000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@JUSTKINGREAL"},
  {"name":"Alash Pride TV","handle":"AlashPrideTV","s":1040000,"v":135000,"c":"Казахстан","t":"Спорт","l":"https://youtube.com/@AlashPrideTV"},
  {"name":"Story-Bytes","handle":"StoryBytes","s":1010000,"v":1719000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@StoryBytes"},
  {"name":"СМЕХОВОРОТ","handle":"Smekhovorot","s":973000,"v":967000,"c":"Казахстан","t":"Юмор","l":"https://youtube.com/@Smekhovorot"},
  {"name":"AnimalisTop","handle":"AnimalisTop","s":948000,"v":9452000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@AnimalisTop"},
  {"name":"Zhuldyz TV","handle":"ZhuldyzTV","s":928000,"v":199000,"c":"Казахстан","t":"Музыка","l":"https://youtube.com/@ZhuldyzTV"},
  {"name":"SADRADDIN","handle":"SADRADDIN","s":914000,"v":10703000,"c":"Казахстан","t":"Музыка","l":"https://youtube.com/@SADRADDIN"},
  {"name":"Интересное в исламе","handle":"InteresnoeVIslame","s":901000,"v":633000,"c":"Казахстан","t":"Образование","l":"https://youtube.com/@InteresnoeVIslame"},
  {"name":"что в кино","handle":"ChtoVKino","s":795000,"v":78000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@ChtoVKino"},
  {"name":"AITYM ZHAKUPOV","handle":"AitymZhakupov","s":792000,"v":323000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@AitymZhakupov"},
  {"name":"Rakhymzhan Zhakaiym","handle":"RakhymzhanZhakaiym","s":766000,"v":2086000,"c":"Казахстан","t":"Общие","l":"https://youtube.com/@RakhymzhanZhakaiym"},
  {"name":"Светские Новости","handle":"SvetskieNovosti","s":762000,"v":292000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@SvetskieNovosti"},
  {"name":"KADRIMMER","handle":"KADRIMMER","s":752000,"v":1002000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@KADRIMMER"},
  {"name":"NURKZ","handle":"NURKZ","s":749000,"v":164000,"c":"Казахстан","t":"Новости","l":"https://youtube.com/@NURKZ"},
  {"name":"Joe Vite","handle":"JoeVite","s":710000,"v":775000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@JoeVite"},
  {"name":"БИНОКЛЬ ВРЕМЕНИ","handle":"BinoklVremeni","s":698000,"v":426000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@BinoklVremeni"},
  {"name":"Masha Klevo","handle":"MashaKlevo","s":680000,"v":1308000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@MashaKlevo"},
  {"name":"МОТИВАТОР","handle":"Motivator","s":678000,"v":360000,"c":"Казахстан","t":"Образование","l":"https://youtube.com/@Motivator"},
  {"name":"ASG","handle":"ASG","s":674000,"v":363000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@ASG"},
  {"name":"Бешеный Пес","handle":"BeshenyiPes","s":667000,"v":534000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@BeshenyiPes"},
  {"name":"ПРЕМИЯ ДАРВИНА","handle":"PremiyaDarvina","s":653000,"v":3922000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@PremiyaDarvina"},
  {"name":"ДЕТКИ АНГЕЛЫ","handle":"DetkiAngely","s":631000,"v":243000,"c":"Казахстан","t":"Юмор","l":"https://youtube.com/@DetkiAngely"},
  {"name":"SkillerHome","handle":"SkillerHome","s":2830000,"v":7278000,"c":"Казахстан","t":"Спорт","l":"https://youtube.com/@SkillerHome"},
  {"name":"OKRESTNYY","handle":"OKRESTNYY","s":436000,"v":624000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@OKRESTNYY"},
  {"name":"an4ous","handle":"an4ous","s":371000,"v":453000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@an4ous"},
  {"name":"ДУШНИЛА","handle":"Dushnila","s":295000,"v":2926000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@Dushnila"},
  {"name":"Shame","handle":"Shame","s":224000,"v":267000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@Shame"},
  {"name":"Alish Motion","handle":"AlishMotion","s":216000,"v":3495000,"c":"Казахстан","t":"Красота","l":"https://youtube.com/@AlishMotion"},
  {"name":"Cybrix","handle":"Cybrix","s":182000,"v":172000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@Cybrix"},
  {"name":"Shorts Factory","handle":"ShortsFactory","s":115000,"v":1075000,"c":"Казахстан","t":"Развлечения","l":"https://youtube.com/@ShortsFactory"},
  {"name":"Margaritka","handle":"Margaritka","s":99700,"v":1354000,"c":"Казахстан","t":"Красота","l":"https://youtube.com/@Margaritka"}
];

// Sort check: sorted by subscribers descending
YOUTUBE_DB.sort((a,b) => b.s - a.s);

const YOUTUBE_CITIES=[...new Set(YOUTUBE_DB.map(x=>x.c))];
const YOUTUBE_CATS=[...new Set(YOUTUBE_DB.map(x=>x.t))];
